import {test,expect} from 'bun:test';
import {randomUUID} from 'node:crypto';
import {resolve} from 'node:path';
import {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {InMemoryTransport} from '@modelcontextprotocol/sdk/inMemory.js';
import {registerDesktopTools} from '../src/desktop-runtime';
import {inspectParticipant} from '../src/participants';
import {nativeFixture,until} from './collaboration-fixture';
const root=resolve(import.meta.dir,'..');
test('Claude MCP initiates and sends through Codex reception; Codex reads and replies through the same core',async()=>{
 const f=await nativeFixture(),codex=await f.connect(),server=new McpServer({name:'claude-fixture',version:'1'}),client=new Client({name:'fixture',version:'1'});
 const p=await inspectParticipant({configDir:f.config,stateDir:f.state,ipcPath:f.desktop.path},f.peerId,'claude');
 const runtime=registerDesktopTools(server,{configDir:f.config,stateDir:f.state,ipcPath:f.desktop.path,codexHome:f.root,pluginRoot:root,authenticate:async()=>({provider:'claude',sessionId:p.sessionId,pid:p.pid,procStart:p.procStart,project:p.project.directory,binding:{method:'fixture_only',generation:'fixture',surface:'claude-desktop',evidence:['fixture_only']}})});
 const [a,b]=InMemoryTransport.createLinkedPair();await Promise.all([server.connect(a),client.connect(b)]);
 const call=async(name:string,args:Record<string,unknown>)=>{const r=await client.callTool({name:'desktop_collaboration_'+name,arguments:args});if(r.isError)throw new Error(JSON.stringify(r.content));return JSON.parse((r.content as {text:string}[])[0]!.text);};
 try{await call('discover',{});await f.call(codex,'desktop_collaboration_discover',{});
  const run=await call('prepare',{requestId:randomUUID(),peerId:f.desktop.threadId,context:{objective:'reverse host smoke'},limits:{maxMessages:8,maxSeconds:300},openPanel:false});expect(run.initiator.provider).toBe('claude');await call('start',{runId:run.id,supervised:true});
  const id=randomUUID();const sent=await call('send',{runId:run.id,messageId:id,text:'CLAUDE_TO_CODEX_42'});expect(['socket-written','started','steered','delivered','consumed']).toContain(sent.status);await until(()=>f.desktop.submissions.length===1);expect(JSON.stringify(f.desktop.submissions[0])).toContain('CLAUDE_TO_CODEX_42');expect(JSON.stringify(f.desktop.submissions[0])).not.toContain('capability');expect(JSON.stringify(f.desktop.submissions[0])).toContain('core_admitted');
  const status=await f.call(codex,'desktop_collaboration_status',{runId:run.id});expect(status.error).toBeFalsy();expect(status.data.messagesUsed).toBe(1);expect(status.data.messages[0].src.provider).toBe('claude');
  const reply=await f.call(codex,'desktop_collaboration_send',{runId:run.id,messageId:randomUUID(),replyTo:id,text:'CODEX_TO_CLAUDE_42'});expect(reply.error).toBeFalsy();expect(reply.data.attribution).toBe('authenticated_mcp_caller');await until(()=>f.frames.some(x=>x.type==='user'&&x.message.content.includes('CODEX_TO_CLAUDE_42')));
  const nativeReply=f.frames.find(x=>x.type==='user'&&x.message.content.includes('CODEX_TO_CLAUDE_42'))!;if(nativeReply.type!=='user')throw new Error('Expected user frame');expect(nativeReply.message.content).not.toContain('\"capability\":');expect(nativeReply.message.content).toContain('native_claude_not_observed');
  const takeover=await f.call(codex,'desktop_collaboration_control',{runId:run.id,commandId:randomUUID(),expectedRevision:1,control:{action:'pause'}});expect(takeover.error).toBeTruthy();
 }finally{await client.close();await server.close();await runtime.close();await codex.close();await f.close();}
},15000);

test('Codex-origin managed replies inherit the project grant, while Claude initiation remains scoped to explicit reception',async()=>{
 const f=await nativeFixture(false,{reception:'default'}),codex=await f.connect(),server=new McpServer({name:'claude-fixture',version:'1'}),client=new Client({name:'fixture',version:'1'});
 const {ProjectAuthorizations}=await import('../src/project-authorization'),grants=new ProjectAuthorizations(f.state);grants.change({project:f.root,ownerThread:f.desktop.threadId,actionId:randomUUID(),enabled:true,expectedRevision:0,confirmed:true});grants.close();f.bridge.updateRuntime({status:'idle',mode:'bypass'});
 const p=await inspectParticipant({configDir:f.config,stateDir:f.state,ipcPath:f.desktop.path},f.peerId,'claude');
 const runtime=registerDesktopTools(server,{configDir:f.config,stateDir:f.state,ipcPath:f.desktop.path,codexHome:f.root,pluginRoot:root,authenticate:async()=>({provider:'claude',sessionId:p.sessionId,pid:p.pid,procStart:p.procStart,project:f.root,binding:{method:'fixture',generation:'fixture',surface:'claude-desktop',evidence:[]}})}),[a,b]=InMemoryTransport.createLinkedPair();await Promise.all([server.connect(a),client.connect(b)]);
 const call=async(name:string,args:Record<string,unknown>)=>{const r=await client.callTool({name:'desktop_collaboration_'+name,arguments:args});if(r.isError)throw new Error(JSON.stringify(r.content));return JSON.parse((r.content as {text:string}[])[0]!.text)};
 try{await call('discover',{});const run=(await f.call(codex,'desktop_collaboration_prepare',{requestId:randomUUID(),peerId:f.peerId,context:{objective:'grant response'},openPanel:false})).data;expect(run.id).toBeTruthy();expect((await f.call(codex,'desktop_collaboration_start',{runId:run.id,supervised:true})).error).toBeFalsy();const messageId=randomUUID();expect((await f.call(codex,'desktop_collaboration_send',{runId:run.id,messageId,text:'GRANT_REQUEST'})).error).toBeFalsy();await until(()=>f.frames.some(x=>x.type==='user'));
  await Bun.sleep(5);await call('send',{runId:run.id,messageId:randomUUID(),replyTo:messageId,text:'GRANT_RESPONSE'});await until(()=>f.desktop.submissions.length===1);expect(JSON.stringify(f.desktop.submissions)).toContain('GRANT_RESPONSE');expect(f.bridge.policy()).toBe('default');
  await f.call(codex,'desktop_collaboration_control',{runId:run.id,commandId:randomUUID(),expectedRevision:1,control:{action:'finish'}});
  const reverse=await call('prepare',{requestId:randomUUID(),peerId:f.desktop.threadId,context:{objective:'new initiation needs consent'},openPanel:false});expect(reverse.preflight.code).toBe('claude_initiation_requires_chat_accept');await expect(call('start',{runId:reverse.id,supervised:true})).rejects.toThrow('explicitly accept');expect(f.desktop.submissions).toHaveLength(1);
 }finally{await client.close();await server.close();await runtime.close();await codex.close();await f.close()}
},15000);

test('private Claude panel authorizes one run without leaking browser credentials or fabricating agent authorization',async()=>{
 const f=await nativeFixture(false,{reception:'default'}),codex=await f.connect(),server=new McpServer({name:'claude-fixture',version:'1'}),client=new Client({name:'fixture',version:'1'});let privateUrl='';let closePeerPanel=async()=>{};const auto=process.env.CC_CDX_PANEL_AUTO_OPEN;delete process.env.CC_CDX_PANEL_AUTO_OPEN;
 const p=await inspectParticipant({configDir:f.config,stateDir:f.state,ipcPath:f.desktop.path},f.peerId,'claude');f.bridge.updateRuntime({status:'idle',mode:'bypass'});
 const runtime=registerDesktopTools(server,{configDir:f.config,stateDir:f.state,ipcPath:f.desktop.path,codexHome:f.root,pluginRoot:root,openPrivatePanel:async url=>{privateUrl=url},authenticate:async()=>({provider:'claude',sessionId:p.sessionId,pid:p.pid,procStart:p.procStart,project:f.root,binding:{method:'fixture',generation:'fixture',surface:'claude-desktop',evidence:[]}})}),[a,b]=InMemoryTransport.createLinkedPair();await Promise.all([server.connect(a),client.connect(b)]);
 const call=async(name:string,args:Record<string,unknown>)=>{const r=await client.callTool({name:'desktop_collaboration_'+name,arguments:args});if(r.isError)throw new Error(JSON.stringify(r.content));return JSON.parse((r.content as {text:string}[])[0]!.text)};
 try{await call('discover',{});await f.call(codex,'desktop_collaboration_discover',{});const publicPanel=await call('panel',{});expect(publicPanel.url).not.toContain('token');expect(publicPanel.tokenReturned).toBe(false);const origin=new URL(privateUrl).origin,token=new URLSearchParams(new URL(privateUrl).hash.slice(1)).get('token')!;expect(token).toHaveLength(64);
  const session=await fetch(origin+'/api/v1/session',{method:'POST',headers:{Origin:origin},body:JSON.stringify({token})});expect(session.status).toBe(200);const {csrf}=await session.json() as {csrf:string},cookie=session.headers.get('set-cookie')!.split(';')[0]!,secret=cookie.slice(cookie.indexOf('=')+1);await call('panel',{});const freshToken=new URLSearchParams(new URL(privateUrl).hash.slice(1)).get('token')!;expect(freshToken).not.toBe(token);const fresh=await fetch(origin+'/api/v1/session',{method:'POST',headers:{Origin:origin},body:JSON.stringify({token:freshToken})});expect(fresh.status).toBe(200);const replay=await fetch(origin+'/api/v1/session',{method:'POST',headers:{Origin:origin},body:JSON.stringify({token})});expect(replay.status).toBe(401);
  const post=async(path:string,body:unknown)=>{const r=await fetch(origin+'/api/v1/desktop/'+path,{method:'POST',headers:{Origin:origin,Cookie:cookie,'X-CSRF-Token':csrf},body:JSON.stringify(body)});return {status:r.status,data:await r.json() as any}};
  const cp=await inspectParticipant({configDir:f.config,stateDir:f.state,ipcPath:f.desktop.path},f.desktop.threadId,'codex'),peerServer=new McpServer({name:'recipient-panel-fixture',version:'1'}),peerClient=new Client({name:'recipient-panel',version:'1'});let peerUrl='';const peerRuntime=registerDesktopTools(peerServer,{configDir:f.config,stateDir:f.state,ipcPath:f.desktop.path,codexHome:f.root,pluginRoot:root,openPrivatePanel:async url=>{peerUrl=url},authenticate:async()=>({provider:'codex',sessionId:cp.sessionId,pid:cp.pid,procStart:cp.procStart,project:f.root,binding:{method:'fixture',generation:'fixture',surface:cp.surface,evidence:[]}})}),[pa,pb]=InMemoryTransport.createLinkedPair();closePeerPanel=async()=>{await peerClient.close();await peerServer.close();await peerRuntime.close()};await Promise.all([peerServer.connect(pa),peerClient.connect(pb)]);await peerClient.callTool({name:'desktop_collaboration_panel',arguments:{}});const peerOrigin=new URL(peerUrl).origin,peerAuth=await fetch(peerOrigin+'/api/v1/session',{method:'POST',headers:{Origin:peerOrigin},body:JSON.stringify({token:new URLSearchParams(new URL(peerUrl).hash.slice(1)).get('token')})});expect(peerAuth.status).toBe(200);const peerCookie=peerAuth.headers.get('set-cookie')!.split(';')[0]!,peerCsrf=(await peerAuth.json() as {csrf:string}).csrf;const peerPost=async(path:string,body:unknown)=>{const r=await fetch(peerOrigin+'/api/v1/desktop/'+path,{method:'POST',headers:{Origin:peerOrigin,Cookie:peerCookie,'X-CSRF-Token':peerCsrf},body:JSON.stringify(body)});return {status:r.status,data:await r.json() as any}};
  const run=(await post('prepare',{requestId:randomUUID(),peerId:f.desktop.threadId,context:{objective:'Exact panel-only consent'},limits:{maxMessages:8,maxSeconds:300},openPanel:false})).data;expect(run.state).toBe('prepared');expect(run.preflight.readyForCheck).toBe(false);expect((await post('start',{runId:run.id,supervised:true})).status).toBe(409);expect((await post('consent',{runId:run.id,expectedRevision:0})).data.valid).toBe(true);
  await f.bridge.setPolicy('hold');expect((await post('start',{runId:run.id,supervised:true})).status).toBe(409);await f.bridge.setPolicy('default');expect((await peerPost('start',{runId:run.id,supervised:true})).status).toBe(200);const bootstrapId=randomUUID();await call('send',{runId:run.id,messageId:bootstrapId,text:'RUN_CONSENT_BOOTSTRAP'});await until(()=>f.desktop.submissions.length===1);expect(JSON.stringify(f.desktop.submissions)).toContain('panel_session:');expect(f.bridge.policy()).toBe('default');
  const reply=await f.call(codex,'desktop_collaboration_send',{runId:run.id,messageId:randomUUID(),replyTo:bootstrapId,text:'RUN_CONSENT_REPLY_WITHOUT_PROJECT_GRANT'});expect(reply.error).toBeFalsy();await until(()=>f.frames.some(x=>x.type==='user'&&x.message.content.includes('RUN_CONSENT_REPLY_WITHOUT_PROJECT_GRANT')));expect(runtime.store.status(run.id,p).messagesUsed).toBe(2);expect(f.bridge.policy()).toBe('default');
  await f.bridge.setPolicy('hold');const held=await f.call(codex,'desktop_collaboration_send',{runId:run.id,messageId:randomUUID(),replyTo:bootstrapId,text:'HOLD_STILL_WINS'});expect(held.error).toBeTruthy();expect(runtime.store.status(run.id,p).messagesUsed).toBe(2);await f.bridge.setPolicy('default');
  const tools=await client.listTools();expect(tools.tools.some(t=>t.name==='desktop_collaboration_notify')).toBe(false);expect(tools.tools.some(t=>t.name==='desktop_collaboration_consent')).toBe(false);await expect(call('panel_command',{commandId:randomUUID()})).rejects.toThrow('Unknown command');
  const snapshot=await call('status',{runId:run.id});expect(JSON.stringify(snapshot)).not.toContain(secret);expect(JSON.stringify(snapshot)).not.toContain(token);expect(snapshot.events.find((e:any)=>e.type==='started').actor).toStartWith('panel_session:');const id=randomUUID();expect((await peerPost('notify',{runId:run.id,commandId:id})).status).toBe(200);expect((await call('panel_command',{commandId:id})).run.id).toBe(run.id);
  await f.bridge.setPolicy('refuse');await expect(call('send',{runId:run.id,messageId:randomUUID(),text:'REFUSE_WINS'})).rejects.toThrow('refuse');expect(runtime.store.status(run.id,p).messagesUsed).toBe(2);
  const {readdirSync,readFileSync}=await import('node:fs');for(const file of readdirSync(f.state).filter(x=>/sqlite(?:-wal|-shm)?$/.test(x)))expect(readFileSync(resolve(f.state,file)).includes(Buffer.from(secret))).toBe(false);
  const pinned=runtime.store.status(run.id,p).participants;pinned.find(x=>x.provider==='codex')!.procStart='stale-fixture';runtime.store.db.run('UPDATE desktop_runs SET participants=? WHERE id=?',[JSON.stringify(pinned),run.id]);await expect(call('control',{runId:run.id,commandId:randomUUID(),expectedRevision:1,control:{action:'pause'}})).rejects.toThrow('Participant process or project changed');expect((await f.call(codex,'desktop_collaboration_control',{runId:run.id,commandId:randomUUID(),expectedRevision:1,control:{action:'cancel'}})).error).toBeTruthy();expect((await call('control',{runId:run.id,commandId:randomUUID(),expectedRevision:1,control:{action:'cancel'}})).state).toBe('cancelled');expect(runtime.store.activeFor({provider:'codex',sessionId:f.desktop.threadId})).toBeNull();
 }finally{auto===undefined?delete process.env.CC_CDX_PANEL_AUTO_OPEN:process.env.CC_CDX_PANEL_AUTO_OPEN=auto;await closePeerPanel();await client.close();await server.close();await runtime.close();await codex.close();await f.close()}
},15000);

test('scoped implementation through both MCP hosts preserves dirty scope, exact reviews and readiness without executing reported checks',async()=>{
 const {writeFileSync}=await import('node:fs'),{git}=await import('../src/project');const f=await nativeFixture();
 for(const args of [['init','-q'],['config','user.email','fixture@example.invalid'],['config','user.name','Fixture']])expect((await git(f.root,args)).code).toBe(0);
 writeFileSync(resolve(f.root,'.gitignore'),'*\n!.gitignore\n!codex.txt\n!claude.txt\n');writeFileSync(resolve(f.root,'codex.txt'),'base\n');writeFileSync(resolve(f.root,'claude.txt'),'base\n');expect((await git(f.root,['add','.'])).code).toBe(0);expect((await git(f.root,['commit','-qm','base'])).code).toBe(0);
 const codex=await f.connect(),server=new McpServer({name:'claude-fixture',version:'1'}),client=new Client({name:'fixture',version:'1'}),p=await inspectParticipant({configDir:f.config,stateDir:f.state,ipcPath:f.desktop.path},f.peerId,'claude');
 const runtime=registerDesktopTools(server,{configDir:f.config,stateDir:f.state,ipcPath:f.desktop.path,codexHome:f.root,pluginRoot:root,authenticate:async()=>({provider:'claude',sessionId:p.sessionId,pid:p.pid,procStart:p.procStart,project:f.root,binding:{method:'fixture',generation:'fixture',surface:'claude-desktop',evidence:[]}})}),[a,b]=InMemoryTransport.createLinkedPair();await Promise.all([server.connect(a),client.connect(b)]);
 const call=async(name:string,args:Record<string,unknown>)=>{const r=await client.callTool({name:'desktop_collaboration_'+name,arguments:args});if(r.isError)throw new Error(JSON.stringify(r.content));return JSON.parse((r.content as {text:string}[])[0]!.text)};
 try{await call('discover',{});const run=await call('prepare',{requestId:randomUUID(),peerId:f.desktop.threadId,context:{objective:'scoped fixture'},implementation:{strategy:'files',workspaces:{codex:{root:f.root,paths:['codex.txt']},claude:{root:f.root,paths:['claude.txt']}},requiredChecks:['diff']},openPanel:false});expect(run.implementation.plan.isolation).toBe('agreement_only');await call('start',{runId:run.id,supervised:true});writeFileSync(resolve(f.root,'claude.txt'),'peer change\n');
 const opId=randomUUID(),capture=await call('implementation',{runId:run.id,operationId:opId,action:{action:'capture'}});expect(capture.candidate.version).toBe(1);expect((await call('implementation',{runId:run.id,operationId:randomUUID(),action:{action:'capture'}})).unchanged).toBe(true);
 expect((await call('status',{runId:run.id})).results).toHaveLength(1);const diff=await git(f.root,['diff','--check']);await call('implementation',{runId:run.id,operationId:randomUUID(),action:{action:'check',check:{candidateHash:capture.candidate.contentHash,name:'diff',command:'git diff --check',exitCode:diff.code,summary:'Fixture actually ran git diff --check'}}});
 const report={kind:'review',resultId:capture.candidate.resultId,version:1,verdict:'agree',disagreements:[]};expect((await f.call(codex,'desktop_collaboration_report',{runId:run.id,reportId:randomUUID(),report,text:'Fixture peer declaration'})).error).toBeFalsy();const ready=await call('implementation',{runId:run.id,operationId:randomUUID(),action:{action:'inspect'}});expect(ready.ready).toBe(true);expect(ready.testsVerifiedByCore).toBe(false);expect(ready.validatedConsensus).toBe(false);
 await call('send',{runId:run.id,messageId:randomUUID(),text:'DIRTY_SCOPE_ALLOWED'});await until(()=>f.desktop.submissions.length===1);writeFileSync(resolve(f.root,'claude.txt'),'after review\n');expect((await call('implementation',{runId:run.id,operationId:randomUUID(),action:{action:'inspect'}})).ready).toBe(false);
 }finally{await client.close();await server.close();await runtime.close();await codex.close();await f.close()}
},20000);
