import {test,expect} from 'bun:test';
import {mkdtempSync,rmSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {DesktopRunStore,type Principal} from '../src/desktop-runs';
import {RunStore} from '../src/runs';
import type {Participant} from '../src/participants';
function fixture(provider:'codex'|'claude'='claude',messages:number|null=8){const root=mkdtempSync('/tmp/desktop-runs-');let now=10000;const store=new DesktopRunStore(root,()=>now);const participants=['codex','claude'].map((p,i)=>({provider:p,sessionId:randomUUID(),name:'Same',surface:p==='codex'?'codex-claude-uds-bridge':'claude-desktop',pid:100+i,procStart:'fixed',socketPath:'/tmp/'+i+'.sock',version:'test',status:'idle',project:{directory:root,kind:'directory',worktree:root,commonGitDir:null,head:null,branch:null,dirty:null,diffHash:null,statusHash:null,untrackedPaths:[],untrackedSnapshot:null}})) as Participant[];const own=participants.find(x=>x.provider===provider)!;const peer=participants.find(x=>x!==own)!;const id=store.prepare(own,randomUUID(),{objective:'Symmetric run'},{maxMessages:messages,maxSeconds:60},participants);const holder='executor';store.registerExecutor(holder,process.pid,Bun.spawnSync(['ps','-o','lstart=','-p',String(process.pid)],{env:{...process.env,LC_ALL:'C',TZ:'UTC'}}).stdout.toString().trim());store.start(id,own,holder);return {root,store,own,peer,id,holder,participants,setTime:(n:number)=>now=n,close(){store.close();rmSync(root,{recursive:true,force:true});}};}
for(const provider of ['claude','codex'] as const)test(provider+' initiates; both attributed participants send and read, peer cannot control',()=>{const f=fixture(provider);try{
 const msg=randomUUID(),s=f.store.reserve(f.id,f.own,msg,'task');expect(s.header).not.toBeNull();const transport=randomUUID();f.store.claim(f.id,f.own,msg,transport,s.message.epoch,'wire');f.store.transport(transport,'socket-written');
 expect(f.store.admit(f.peer,f.own,s.header!,transport,'wire')).toBe(true);expect(f.store.admit(f.peer,f.own,s.header!,transport,'wire')).toBe(true);expect(f.store.claimRecipient(transport)).toBe(true);expect(f.store.claimRecipient(transport)).toBe(false);f.store.transport(transport,'delivered');
 const reply=f.store.reserve(f.id,f.peer,randomUUID(),'reply',msg);expect(reply.message.src).toBe(f.peer.provider+':'+f.peer.sessionId);expect(f.store.status(f.id,f.peer).messagesUsed).toBe(2);
 expect(()=>f.store.control(f.id,f.peer,randomUUID(),1,{action:'pause'},f.holder)).toThrow('initiating');expect(()=>f.store.status(f.id,{provider:'claude',sessionId:randomUUID()})).toThrow('participant');
 expect(JSON.stringify(f.store.status(f.id,f.own))).not.toContain(s.header!.capability);
 }finally{f.close();}});
test('capability is bound to source, destination, context, attempt and epoch; budget counts once',()=>{const f=fixture();try{const s=f.store.reserve(f.id,f.own,randomUUID(),'one'),t=randomUUID();f.store.claim(f.id,f.own,s.message.id,t,s.message.epoch,'wire');
 expect(f.store.admit(f.peer,f.own,{...s.header!,capability:'0'.repeat(64)},t,'wire')).toBe(false);expect(f.store.admit(f.own,f.peer,s.header!,t,'wire')).toBe(false);expect(f.store.admit(f.peer,f.own,{...s.header!,contextVersion:2},t,'wire')).toBe(false);expect(f.store.admit(f.peer,f.own,s.header!,randomUUID(),'wire')).toBe(false);expect(f.store.status(f.id,f.own).messagesUsed).toBe(1);
 expect(f.store.reserve(f.id,f.own,s.message.id,'one').reused).toBe(true);expect(()=>f.store.reserve(f.id,f.own,s.message.id,'changed')).toThrow('different');expect(()=>f.store.claim(f.id,f.own,s.message.id,t,s.message.epoch,'wire')).toThrow('already');
 }finally{f.close();}});
test('unknown survives restart, cannot resend or resume, and deadline releases both claims',()=>{const f=fixture();try{const s=f.store.reserve(f.id,f.own,randomUUID(),'one'),t=randomUUID();f.store.claim(f.id,f.own,s.message.id,t,s.message.epoch,'wire');f.store.transport(t,'unknown');const other=new DesktopRunStore(f.root,()=>10000);try{expect(other.status(f.id,f.peer).state).toBe('blocked');expect(other.reserve(f.id,f.own,s.message.id,'one').reused).toBe(true);}finally{other.close();}
 expect(()=>f.store.reserve(f.id,f.peer,randomUUID(),'second')).toThrow('blocked');expect(()=>f.store.control(f.id,f.own,randomUUID(),f.store.status(f.id,f.own).coordination.revision,{action:'resume'},f.holder)).toThrow('Uncertain');f.setTime(70000);expect(f.store.status(f.id,f.own).state).toBe('limit_reached');expect(f.store.db.query('SELECT * FROM desktop_claims').all()).toHaveLength(0);
 }finally{f.close();}});
test('unlimited message budget still has a deadline; legacy writers cannot steal Desktop claims',()=>{const f=fixture('codex',null);try{expect(f.store.status(f.id,f.own).limits.maxMessages).toBeNull();const legacy=new RunStore(f.root);try{const id=legacy.prepare(f.own.sessionId,randomUUID(),{objective:'legacy',constraints:[],references:[],priorAnalysis:{}},{maxMessages:4,maxSeconds:60},f.participants,{});expect(()=>legacy.start(id,f.own.sessionId)).toThrow('Desktop collaboration');expect(f.store.status(f.id,f.peer).state).toBe('active');}finally{legacy.close();}
 }finally{f.close();}});
test('result versions and exact peer reviews survive context changes without inventing consensus',()=>{const f=fixture();try{const resultId=randomUUID();f.store.report(f.id,f.own,randomUUID(),{kind:'result',resultId,version:1,title:'v1',disagreements:[]},'first');f.store.report(f.id,f.peer,randomUUID(),{kind:'review',resultId,version:1,verdict:'agree',disagreements:[]},'reviewed');expect(f.store.status(f.id,f.own).reviews[0]!.current).toBe(true);f.store.report(f.id,f.own,randomUUID(),{kind:'result',resultId,version:2,title:'v2',disagreements:[]},'second');expect(f.store.status(f.id,f.peer).reviews[0]!.current).toBe(false);expect(()=>f.store.report(f.id,f.peer,randomUUID(),{kind:'result',resultId,version:3,title:'stolen',disagreements:[]},'bad')).toThrow('authored');expect(f.store.status(f.id,f.own).validatedConsensus).toBe(false);
 }finally{f.close();}});

test('wire modification and a raw transport cannot consume an issued capability',()=>{const f=fixture();try{const r=f.store.reserve(f.id,f.own,randomUUID(),'exact body'),t=randomUUID();f.store.claim(f.id,f.own,r.message.id,t,r.message.epoch,'wire');expect(f.store.admit(f.peer,f.own,r.header!,t,'tampered')).toBe(false);expect(f.store.admit(f.peer,f.own,r.header!,t,'wire')).toBe(true);expect(f.store.claimRecipient(t)).toBe(true);expect(f.store.admit(f.peer,f.own,r.header!,t,'wire')).toBe(false);}finally{f.close()}});
test('unknown executors fail closed and heartbeat renews only the registered holder without changing epoch',()=>{const f=fixture();try{expect(()=>f.store.control(f.id,f.own,randomUUID(),1,{action:'recover'},'unknown')).toThrow('live executor');f.store.db.run("UPDATE desktop_runs SET lease_holder='missing' WHERE id=?",[f.id]);expect(()=>f.store.reserve(f.id,f.own,randomUUID(),'no')).toThrow('lease expired');expect(f.store.fence(f.id,1)).toBe(false);f.store.db.run('UPDATE desktop_runs SET lease_holder=? WHERE id=?',[f.holder,f.id]);f.setTime(50000);f.store.heartbeat(f.holder);expect(f.store.status(f.id,f.own).coordination.lease.expiresAt).toBe(350000);expect(f.store.status(f.id,f.own).coordination.lease.epoch).toBe(1);}finally{f.close()}});
test('recovering an unclaimed reservation marks it not-sent without refund, replay or stale-epoch writing',()=>{const f=fixture();try{const r=f.store.reserve(f.id,f.own,randomUUID(),'never claimed');f.store.control(f.id,f.own,randomUUID(),1,{action:'recover'},f.holder);expect(f.store.message(r.message.id)!.status).toBe('not-sent');expect(f.store.status(f.id,f.own).messagesUsed).toBe(1);expect(f.store.reserve(f.id,f.own,r.message.id,'never claimed').reused).toBe(true);expect(()=>f.store.claim(f.id,f.own,r.message.id,randomUUID(),1,'wire')).toThrow('Stale');f.store.control(f.id,f.own,randomUUID(),2,{action:'resume'},f.holder);expect(f.store.fence(f.id,1)).toBe(false);expect(f.store.fence(f.id,2)).toBe(true);}finally{f.close()}});
test('a panel scope is still a participant scope, and consent expires or is invalidated by exact context',()=>{const f=fixture();try{const stranger={provider:'claude' as const,sessionId:randomUUID()};expect(f.store.list(stranger,true)).toHaveLength(0);expect(()=>f.store.status(f.id,stranger,true)).toThrow('participant');expect(()=>f.store.control(f.id,stranger,randomUUID(),1,{action:'pause'},f.holder,'panel_session:test')).toThrow('participant');expect(()=>f.store.consent(f.id,f.own,'agent:claimed',1)).toThrow('panel');expect(f.store.consent(f.id,f.own,'panel_session:nonsecret',1).valid).toBe(true);f.store.control(f.id,f.own,randomUUID(),1,{action:'context',context:{objective:'changed'}},f.holder);expect(f.store.consentStatus(f.id).valid).toBe(false);f.store.consent(f.id,f.own,'panel_session:nonsecret',2);f.store.revokeConsent(f.id,f.own,'panel_session:nonsecret');expect(f.store.consentStatus(f.id).valid).toBe(false);f.store.consent(f.id,f.own,'panel_session:nonsecret',2);f.setTime(70000);expect(f.store.consentStatus(f.id).valid).toBe(false);}finally{f.close()}});

test('optional registered-analysis barrier hides reports across hosts, re-arms on context and records a closure with objections without forcing agreement',()=>{
 const f=fixture('codex');try{
 f.store.coordination.prepare(f.id,f.participants.map(p=>p.provider+':'+p.sessionId) as [string,string],{initialBarrier:true});
 const ownTask={taskId:randomUUID(),intent:'analyze' as const};f.store.control(f.id,f.own,randomUUID(),1,{action:'task',task:ownTask,assignee:'self'},f.holder);
 expect(()=>f.store.reserve(f.id,f.own,randomUUID(),'analysis not yet for exchange')).toThrow('Initial barrier');const task={taskId:randomUUID(),intent:'analyze' as const},msg=randomUUID(),sent=f.store.reserve(f.id,f.own,msg,'Objective only; record your analysis locally',undefined,task),transport=randomUUID();f.store.claim(f.id,f.own,msg,transport,sent.message.epoch,'wire');f.store.transport(transport,'socket-written');
 f.store.report(f.id,f.peer,randomUUID(),{kind:'response',taskId:task.taskId,declaredState:'analysis',disagreements:[]},'Peer analysis private until both recorded');expect(f.store.status(f.id,f.own).reports).toHaveLength(0);expect(f.store.status(f.id,f.peer).reports).toHaveLength(1);
 f.store.report(f.id,f.own,randomUUID(),{kind:'response',taskId:ownTask.taskId,declaredState:'analysis',disagreements:[]},'Owner analysis');expect(f.store.status(f.id,f.own).reports).toHaveLength(2);expect(f.store.status(f.id,f.own).coordination.barrierOpen).toBe(true);
 f.store.control(f.id,f.own,randomUUID(),2,{action:'context',context:{objective:'New context'}},f.holder);expect(f.store.status(f.id,f.peer).coordination.barrierOpen).toBe(false);expect(()=>f.store.reserve(f.id,f.peer,randomUUID(),'early')).toThrow('Initial barrier');
 f.store.control(f.id,f.own,randomUUID(),3,{action:'finish',closure:{summary:'Partial proposal; more analysis needed',disposition:'incomplete'}},f.holder);expect(f.store.status(f.id,f.own).coordination.structured.closure?.consensus).toBe('not_declared');expect(f.store.status(f.id,f.own).state).toBe('completed');
 }finally{f.close()}
});

test('an unstarted draft can be cancelled by its initiator without acquiring claims or starting a deadline',()=>{
 const f=fixture('codex');try{
  const id=f.store.prepare(f.own,randomUUID(),{objective:'Unstarted draft'},{maxMessages:4,maxSeconds:60},f.participants);
  expect(()=>f.store.control(id,f.peer,randomUUID(),0,{action:'cancel'},f.holder)).toThrow('initiating');
  const closed=f.store.control(id,f.own,randomUUID(),0,{action:'cancel'},f.holder);expect(closed.state).toBe('cancelled');expect(f.store.status(id,f.own).deadline).toBeNull();
  expect(f.store.db.query('SELECT 1 FROM desktop_claims WHERE run_id=?').get(id)).toBeNull();expect(f.store.status(f.id,f.own).state).toBe('active');
 }finally{f.close()}
});

test('the bound participant panel can start, while peer MCP and an unrelated panel cannot',()=>{const f=fixture();try{f.store.control(f.id,f.own,randomUUID(),1,{action:'cancel'},f.holder);const id=f.store.prepare(f.own,randomUUID(),{objective:'Scoped participant panel'},{maxMessages:4,maxSeconds:60},f.participants);expect(()=>f.store.start(id,f.peer,f.holder)).toThrow('initiating');expect(()=>f.store.start(id,{provider:'codex',sessionId:randomUUID()},f.holder,'panel_session:fixture')).toThrow('participant');expect(()=>f.store.start(id,f.peer,f.holder,'not-a-panel')).toThrow('scoped panel');f.store.start(id,f.peer,f.holder,'panel_session:fixture');expect(f.store.status(id,f.own).state).toBe('active');expect(f.store.status(id,f.own).events.find(e=>e.type==='started')!.actor).toBe('panel_session:fixture');}finally{f.close();}});
