import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {Activity,ArrowLeft,ArrowRight,Check,ChevronRight,Download,FileText,GitCompareArrows,LayoutDashboard,Link2,Loader2,Moon,Pause,Play,Plus,RefreshCw,Search,Settings2,Square,Sun,Wifi,WifiOff} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Card,CardContent,CardHeader,CardTitle,CardDescription} from '@/components/ui/card';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Label} from '@/components/ui/label';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Alert,AlertDescription} from '@/components/ui/alert';
import {Progress} from '@/components/ui/progress';
import {Switch} from '@/components/ui/switch';
import {ImplementationOptions,ImplementationDetail,type ImplementationInput,type ImplementationState,type Preset} from './Implementation';
import {Separator} from '@/components/ui/separator';

type Participant={sessionId:string;name:string;cwd:string;provider:'codex'|'claude';status:string;eligibleSurface:boolean;panelReceiver:boolean|null;projectAuthorizationReceiver:boolean|null;implementationReceiver?:boolean|null};
type Summary={id:string;ownerThread:string;objective:string;state:string;createdAt:number;reason:string|null};
type Command={id:string;state:string;action:string;runId:string|null;error:string|null;inspection?:string|null};
type Report={id:string;created_at:number;author:string;body:string;contentHash:string;contextVersion:number;report:{kind:string;title?:string;resultId?:string;version?:number;verdict?:string}};
type Run=Summary&{implementation:ImplementationState|null;context:{objective:string;constraints:string[];references:string[];priorAnalysis:{codex?:string;claude?:string}};contextVersion:number;participants:{sessionId:string;name:string;provider:string;project:{directory:string}}[];limits:{maxMessages:number;maxSeconds:number};messagesUsed:number;deadline:number|null;coordination:{revision:number;phase:string;initialBarrier:boolean;barrierOpen:boolean;lease:{ownedByCaller:boolean;expiresAt:number|null}}|null;reports:Report[];results:(Report&{reviewState:string;reviewedByBoth:boolean})[];reviews:(Report&{current:boolean;targetHash:string})[];disagreements:{author:string;reportId:string;text:string}[];closure:{summary?:string;disposition?:string;result?:{resultId:string;version:number}}|null;events:{sequence:number;type:string;actor:string;at:number}[];messages:{id:string;direction:string;peer_id:string;text:string|null;status:string;contentRedacted:boolean;created_at:number;evidence:{consumed_at:number|null;responded_at:number|null}|null}[];pendingTasks:string[]};
// A name is a label, not an identity. Expand the suffix if homonyms share a prefix.
function participantLabel(p:Participant,participants:Participant[]){
 const homonyms=participants.filter(other=>other.provider===p.provider&&other.name===p.name&&other.sessionId!==p.sessionId);
 if(!homonyms.length)return p.name;
 let length=Math.min(8,p.sessionId.length);
 while(length<p.sessionId.length&&homonyms.some(other=>other.sessionId.slice(0,length)===p.sessionId.slice(0,length)))length++;
 return `${p.name} · ${p.sessionId.slice(0,length)}`;
}
const stateNames:Record<string,string>={prepared:'Preparada',active:'En curso',paused:'Pausada',blocked:'Bloqueada',recovery_required:'Requiere recuperación',completed:'Finalizada',cancelled:'Cancelada',limit_reached:'Límite alcanzado'};
const reasonNames:Record<string,string>={owner_pause:'Pausada desde el chat propietario.',deadline:'Se alcanzó el tiempo máximo.',message_budget:'Se alcanzó el máximo de mensajes.',lease_expired:'El controlador necesita recuperación.',recovered_paused:'Recuperada en pausa. Puedes reanudarla.',unfinished_delivery:'Hay una entrega incierta que requiere revisión.','Cancelled from the local panel':'Cancelada desde el panel local.'};
const phaseNames:Record<string,string>={context:'Contexto',independent_analysis:'Análisis inicial',critique:'Contraste',verification:'Verificación',synthesis:'Síntesis',final_review:'Revisión final'};
const commandNames:Record<string,string>={queued:'Orden guardada',waking:'Activando el chat',notified:'Esperando al agente',applying:'Aplicando',applied:'Aplicada',failed:'No aplicada',unknown:'Entrega incierta',application_uncertain:'Aplicación interrumpida'};
const terminal=(state:string)=>['completed','cancelled','limit_reached'].includes(state);
const date=(time:number)=>new Intl.DateTimeFormat('es',{dateStyle:'medium',timeStyle:'short'}).format(time);
let csrf='';
async function api<T>(path:string,body?:unknown):Promise<T>{let response:Response;try{response=await fetch('/api/v1/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:body===undefined?undefined:JSON.stringify(body)})}catch{throw new Error('El servicio local no está disponible. Si lo has reiniciado, abre su nuevo enlace privado.')}if(!response.ok){const err=await response.json().catch(()=>({error:'No se pudo conectar'}));throw new Error(err.error)}return response.json()}
function Body({text}:{text:string}){return text.length<1600?<p className="prose-text text-sm leading-7">{text}</p>:<div><p className="prose-text text-sm leading-7">{text.slice(0,1100)}…</p><details className="mt-3 text-sm"><summary className="cursor-pointer text-primary">Leer aportación completa</summary><p className="prose-text mt-3 leading-7">{text}</p></details></div>}
function State({state}:{state:string}){return <Badge variant="outline" className={state==='active'?'border-emerald-300 bg-emerald-50 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200':''}><span className={`mr-1.5 size-1.5 rounded-full ${state==='active'?'bg-emerald-500':'bg-muted-foreground'}`}/>{stateNames[state]??state}</Badge>}
function Field({label,children,hint}:{label:string;children:React.ReactNode;hint?:string}){return <div className="space-y-2"><Label>{label}</Label>{children}{hint&&<p className="text-xs text-muted-foreground">{hint}</p>}</div>}
export default function App(){
 const [presets,setPresets]=useState<Preset[]>([]),[ready,setReady]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[view,setView]=useState<'home'|'new'|'detail'|'diagnostic'|'authorization'>(()=>sessionStorage.getItem('selectedRun')?'detail':'home'),[bound,setBound]=useState<string|null>(null),[runs,setRuns]=useState<Summary[]>([]),[participants,setParticipants]=useState<Participant[]>([]),[commands,setCommands]=useState<Command[]>([]),[run,setRun]=useState<Run|null>(null),[selected,setSelected]=useState(()=>sessionStorage.getItem('selectedRun')??''),[search,setSearch]=useState(''),[connected,setConnected]=useState(false),[dark,setDark]=useState(()=>localStorage.getItem('theme')?localStorage.getItem('theme')==='dark':matchMedia('(prefers-color-scheme: dark)').matches);
 const [serviceVersion,setServiceVersion]=useState('');const [continued,setContinued]=useState<Run|null>(null);const [controlBusy,setControlBusy]=useState(false);const [controlNotice,setControlNotice]=useState<Command|null>(null);const controlLock=useRef(false);const controlRequest=useRef<{key:string;id:string}|null>(null);const cursor=useRef<Record<string,number>>({});const selection=useRef(selected);selection.current=selected;
 useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.setItem('theme',dark?'dark':'light')},[dark]);
 useEffect(()=>{(async()=>{try{const token=new URLSearchParams(location.hash.slice(1)).get('token');if(token){const auth=await api<{csrf:string;ownerThread:string|null}>('session',{token});csrf=auth.csrf;setBound(auth.ownerThread);history.replaceState(null,'',location.pathname);}const health=await api<{csrf:string;ownerThread:string|null;version:string}>('health');csrf=health.csrf;setBound(health.ownerThread);setServiceVersion(health.version);setPresets(await api<Preset[]>('presets'));setReady(true)}catch(e){setError((e as Error).message)}})()},[]);
 const load=useCallback(async()=>{try{const [r,p,c]=await Promise.all([api<Summary[]>('runs'),api<Participant[]>('participants'),api<Command[]>('commands')]);setRuns(r);setParticipants(p);setCommands(c);if(selection.current){const id=selection.current;const detail=await api<Run>('runs/'+id);if(selection.current===id)setRun(detail)}setConnected(true)}catch(e){setConnected(false);setError((e as Error).message)}},[]);
 useEffect(()=>{if(!ready)return;void load();const timer=setInterval(()=>void load(),2500);return()=>clearInterval(timer)},[ready,load]);
 useEffect(()=>{if(!ready||!selected)return;sessionStorage.setItem('selectedRun',selected);setRun(null);void load();let timer:ReturnType<typeof setTimeout>|undefined;const stream=new EventSource(`/api/v1/runs/${selected}/stream?after=${cursor.current[selected]??0}`);stream.addEventListener('update',e=>{const event=e as MessageEvent;cursor.current[selected]=Number(event.lastEventId);if(!timer)timer=setTimeout(()=>{timer=undefined;void load()},100)});stream.onopen=()=>setConnected(true);stream.onerror=()=>setConnected(false);return()=>{stream.close();if(timer)clearTimeout(timer)}},[ready,selected,load]);
 const choose=(id:string)=>{setError('');setNotice('');setControlNotice(null);setSelected(id);setView('detail')};
 const newRun=(previous:Run|null=null)=>{setContinued(previous);setError('');setNotice('');setControlNotice(null);setView('new')};
 const attention=commands.find(c=>['unknown','application_uncertain','failed'].includes(c.state)&&(!c.runId||c.runId===selected));
 const pending=commands.find(c=>['queued','waking','notified','applying'].includes(c.state)&&(!c.runId||c.runId===selected));
 const noticeCommand=controlNotice&&(commands.find(c=>c.id===controlNotice.id)??controlNotice);
 const noticeText=noticeCommand?commandNames[noticeCommand.state]+': '+({pause:'pausar',resume:'reanudar',recover:'recuperar',cancel:'cancelar',input:'añadir instrucción',implementation:'actualizar implementación'} as Record<string,string>)[noticeCommand.action]:notice;
 const control=async(action:string,text?:string,work?:Record<string,unknown>)=>{if(!run?.coordination||controlLock.current)return false;controlLock.current=true;setControlBusy(true);try{setError('');const owner=run.participants.find(p=>p.provider==='codex')!;const command={action,runId:run.id,expectedRevision:run.coordination.revision,...(text?{text}:{}),...(work?{work}:{})};const key=JSON.stringify(command);if(controlRequest.current?.key!==key)controlRequest.current={key,id:crypto.randomUUID()};const c=await api<Command>('commands',{commandId:controlRequest.current.id,ownerThread:run.ownerThread,project:owner.project.directory,command});setCommands(current=>[c,...current.filter(old=>old.id!==c.id)]);setNotice('');setControlNotice(c);void load();return true}catch(e){setError((e as Error).message);return false}finally{controlLock.current=false;setControlBusy(false)}};

 if(!ready)return <main className="mx-auto max-w-lg p-10"><Link2 className="mb-6 size-10 text-primary"/><h1 className="text-2xl font-semibold">Conectar al puente</h1><p className="mt-3 text-muted-foreground">Abre el enlace privado que devuelve el comando de panel. El acceso se limita a este servicio local.</p>{error?<Alert className="mt-6"><AlertDescription>{error}</AlertDescription></Alert>:<Loader2 className="mt-6 animate-spin"/>}</main>;
 return <div className="shell"><aside className="rail"><div className="flex items-center gap-3 px-2"><div className="rounded-lg bg-primary p-2 text-primary-foreground"><Link2 className="size-5"/></div><div><p className="text-base font-semibold tracking-tight">CC–CDX</p><p className="text-[11px] text-muted-foreground">Dos perspectivas. Un proyecto.</p></div></div><nav className="mt-10 space-y-1"><Button variant={view==='home'?'secondary':'ghost'} className="w-full justify-start" onClick={()=>setView('home')}><LayoutDashboard/>Colaboraciones</Button><Button variant={view==='new'?'secondary':'ghost'} className="w-full justify-start" onClick={()=>newRun()}><Plus/>Nueva colaboración</Button><Button variant={view==='authorization'?'secondary':'ghost'} className="w-full justify-start" onClick={()=>setView('authorization')}><Check/>Autorización</Button><Button variant={view==='diagnostic'?'secondary':'ghost'} className="w-full justify-start" onClick={()=>setView('diagnostic')}><Settings2/>Diagnóstico</Button></nav><div className="rail-bottom mt-auto space-y-4 px-2"><Separator/><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-xs text-muted-foreground">{connected?<Wifi className="size-3.5"/>:<WifiOff className="size-3.5"/>}{connected?'Panel conectado':'Reconectando'}</span><Button variant="ghost" size="icon" aria-label={dark?'Usar tema claro':'Usar tema oscuro'} onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</Button></div><p className="text-[11px] text-muted-foreground">Local · v{serviceVersion}<br/>La conversación permanece en tus apps.</p></div></aside>
 <main className="workspace"><div aria-live="polite">{error&&<Alert variant="destructive" className="mb-6"><AlertDescription className="flex justify-between gap-3">{error}<button onClick={()=>setError('')} aria-label="Cerrar error">×</button></AlertDescription></Alert>}{noticeText&&<Alert className="mb-6"><AlertDescription>{noticeText}</AlertDescription></Alert>}{attention&&<Alert className="mb-5"><AlertDescription>{commandNames[attention.state]}. Consulta el estado antes de otra acción; esta orden no se reenviará automáticamente. {attention.error} {attention.inspection}</AlertDescription></Alert>}{pending&&<p className="mb-5 flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="size-3.5 animate-spin"/>{commandNames[pending.state]}. El estado de la colaboración cambia cuando el chat aplica la orden.</p>}</div>
 {view==='home'&&<><div className="mb-9 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow mb-2">Espacio de trabajo</p><h1 className="text-3xl font-semibold tracking-tight">Colaboraciones</h1><p className="mt-2 text-muted-foreground">Del primer análisis a una propuesta revisada.</p></div><Button onClick={()=>newRun()}><Plus/>Nueva colaboración</Button></div><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><div className="relative w-72"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input className="pl-9" aria-label="Buscar colaboración" placeholder="Buscar por objetivo…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="flex gap-3 text-xs text-muted-foreground"><span>{runs.filter(r=>!terminal(r.state)).length} abiertas</span><span>·</span><span>{runs.filter(r=>terminal(r.state)).length} cerradas</span></div></div><Card className="overflow-hidden py-0"><div className="grid grid-cols-[1fr_auto] border-b bg-muted/50 px-6 py-3 text-xs text-muted-foreground"><span>Objetivo</span><span>Estado</span></div>{runs.filter(r=>r.objective.toLowerCase().includes(search.toLowerCase())).map(r=><button key={r.id} className="flex w-full items-center justify-between gap-4 border-b px-6 py-5 text-left transition hover:bg-muted/60 last:border-0" onClick={()=>choose(r.id)}><div className="min-w-0"><p className="truncate font-medium">{r.objective}</p><p className="mt-1 text-xs text-muted-foreground">Codex + Claude · {date(r.createdAt)}</p></div><div className="flex items-center gap-3"><State state={r.state}/><ChevronRight className="size-4 text-muted-foreground"/></div></button>)}{runs.length===0&&<div className="p-12 text-center"><GitCompareArrows className="mx-auto mb-4 size-8 text-muted-foreground"/><h2 className="font-medium">Una pregunta, dos perspectivas</h2><p className="mx-auto mt-2 max-w-sm text-muted-foreground">Elige tus conversaciones de Codex y Claude para investigar o revisar juntos.</p><Button className="mt-5" onClick={()=>newRun()}>Crear la primera colaboración</Button></div>}</Card><div className="mt-7 flex items-center gap-2 text-xs text-muted-foreground"><Activity className="size-3.5"/>Los resultados conservan autoría, revisiones y desacuerdos.</div></>}
 {view==='new'&&<NewCollaboration key={continued?.id??'new'} presets={presets} participants={participants} bound={bound} previous={continued} onBack={()=>setView('home')} onError={setError} onCreated={c=>{setNotice('Orden guardada. Codex recibirá el objetivo en el chat seleccionado.');if(c.runId)choose(c.runId);else setView('home');void load()}}/>}
 {view==='detail'&&(run?<RunDetail run={run} pending={!!pending||controlBusy} control={control} onBack={()=>setView('home')} onContinue={()=>newRun(run)}/>:<div className="flex gap-3"><Loader2 className="animate-spin"/>Cargando colaboración…</div>)}
 {view==='authorization'&&<AuthorizationPage participants={participants} bound={bound} onError={setError}/>}
 {view==='diagnostic'&&<Diagnostic participants={participants} bound={bound} onError={setError}/>}
 {commands.some(c=>c.state==='failed'||c.state==='unknown'||c.state==='application_uncertain')&&<details className="mt-10 rounded-lg border p-4 text-xs"><summary className="cursor-pointer text-muted-foreground">Órdenes que requieren atención</summary>{commands.filter(c=>c.state==='failed'||c.state==='unknown'||c.state==='application_uncertain').map(c=><div key={c.id} className="mt-3"><p>{commandNames[c.state]} · {c.action}</p><p className="mt-1 text-muted-foreground">{c.error} {c.inspection}</p>{c.runId&&<Button variant="link" className="px-0" onClick={()=>choose(c.runId!)}>Abrir colaboración</Button>}</div>)}</details>}
 </main></div>
}
function NewCollaboration({presets,participants,bound,previous,onBack,onError,onCreated}:{presets:Preset[];participants:Participant[];bound:string|null;previous:Run|null;onBack:()=>void;onError:(e:string)=>void;onCreated:(c:Command)=>void}){
 const codex=participants.filter(p=>p.provider==='codex'&&(!bound||p.sessionId===bound));const claude=participants.filter(p=>p.provider==='claude'&&p.eligibleSurface);
 const [owner,setOwner]=useState(previous?.ownerThread??bound??codex[0]?.sessionId??''),[peer,setPeer]=useState(previous?.participants.find(p=>p.provider==='claude')?.sessionId??claude.find(p=>p.cwd===codex.find(c=>c.sessionId===owner)?.cwd)?.sessionId??''),[mode,setMode]=useState('free'),[objective,setObjective]=useState(previous?.context.objective??''),[constraints,setConstraints]=useState(previous?.context.constraints.join('\n')??''),[refs,setRefs]=useState(previous?.context.references.join('\n')??''),[startC,setStartC]=useState(previous?'existing':'new'),[startL,setStartL]=useState(previous?'existing':'new');
 const prior=(provider:string)=>previous?.reports.filter(r=>previous.participants.find(p=>p.sessionId===r.author)?.provider===provider).map(r=>`[${provider} · ${r.report.kind}${r.report.version?' · versión '+r.report.version:''} · ${date(r.created_at)}]\n${r.body}`).join('\n\n').slice(-32000)??'';
 const [analysisC,setAnalysisC]=useState(prior('codex')),[analysisL,setAnalysisL]=useState(prior('claude')),[barrier,setBarrier]=useState(false),[messages,setMessages]=useState(24),[minutes,setMinutes]=useState(30),[busy,setBusy]=useState(false),[allowBusy,setAllowBusy]=useState(false),[verified,setVerified]=useState(false),[checkBusy,setCheckBusy]=useState(false);
 const [implementation,setImplementation]=useState<ImplementationInput|undefined>();
 const chosen=codex.find(c=>c.sessionId===owner),other=claude.find(c=>c.sessionId===peer);const request=()=>({commandId:crypto.randomUUID() as string,ownerThread:owner,project:chosen?.cwd??'',command:{action:'create',peerId:peer,context:{objective,constraints:constraints.split('\n').filter(Boolean),references:refs.split('\n').filter(Boolean),priorAnalysis:{...(startC==='existing'?{codex:analysisC}:{}),...(startL==='existing'?{claude:analysisL}:{})}},routine:{mode,starts:{codex:startC,claude:startL}},limits:{maxMessages:messages,maxSeconds:minutes*60},coordination:{initialBarrier:barrier&&startC==='new'&&startL==='new',leaseSeconds:300},revisionPolicy:'same',allowBusyPeer:allowBusy,...(implementation?{implementation}:{}),...(previous?{continuedFrom:previous.id}:{})}});
 const fingerprint=JSON.stringify(request().command);useEffect(()=>setVerified(false),[fingerprint,owner]);const requestId=useRef<{key:string;id:string}|null>(null);
 const valid=!!chosen&&!!other&&objective.trim().length>0&&(startC==='new'||analysisC.trim().length>0)&&(startL==='new'||analysisL.trim().length>0)&&(!implementation||(!!chosen?.implementationReceiver&&implementation.requiredChecks.length>0&&Object.values(implementation.workspaces).every(w=>w.root.trim().length>0&&w.paths.length>0)));
 const preflight=async()=>{setCheckBusy(true);try{await api('preflight',request());setVerified(true)}catch(e){onError((e as Error).message)}finally{setCheckBusy(false)}};
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!valid||!verified||busy)return;setBusy(true);const data=request();const key=JSON.stringify({owner,command:data.command});if(requestId.current?.key!==key)requestId.current={key,id:data.commandId};data.commandId=requestId.current.id;try{onCreated(await api<Command>('commands',data))}catch(e){onError((e as Error).message)}finally{setBusy(false)}};
 return <form onSubmit={submit} className="mx-auto max-w-3xl"><Button type="button" variant="ghost" className="mb-5 -ml-3" onClick={onBack}><ArrowLeft/>Colaboraciones</Button><p className="eyebrow mb-2">{previous?'Continuar desde el resultado':'Preparar un intercambio'}</p><h1 className="mb-2 text-3xl font-semibold tracking-tight">Nueva colaboración</h1><p className="mb-8 text-muted-foreground">Conecta dos conversaciones y define qué queréis resolver.</p>
 <Card><CardHeader><CardTitle>Conversaciones</CardTitle><CardDescription>Selecciona los chats exactos que trabajarán en el proyecto.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="grid gap-5 sm:grid-cols-2"><Field label="Codex"><NativeSelect aria-label="Conversación Codex" className="w-full" value={owner} onChange={e=>setOwner(e.target.value)}><NativeSelectOption value="">Seleccionar conversación</NativeSelectOption>{codex.map(p=><NativeSelectOption key={p.sessionId} value={p.sessionId}>{participantLabel(p,participants)} · {p.status==='idle'?'disponible':'activo'}</NativeSelectOption>)}</NativeSelect></Field><Field label="Claude"><NativeSelect aria-label="Conversación Claude" className="w-full" value={peer} onChange={e=>setPeer(e.target.value)}><NativeSelectOption value="">Seleccionar conversación</NativeSelectOption>{claude.map(p=><NativeSelectOption key={p.sessionId} value={p.sessionId}>{participantLabel(p,participants)} · {p.status==='idle'?'disponible':'activo'}</NativeSelectOption>)}</NativeSelect></Field></div>{chosen&&<p className="flex items-start gap-2 text-xs text-muted-foreground"><FileText className="mt-0.5 size-3.5 shrink-0"/><span className="break-all">{chosen.cwd}{other&&<><br/>{chosen.cwd===other.cwd?'Misma carpeta seleccionada':'La otra conversación está en otra carpeta; se comprobará la identidad del repositorio.'}</>}</span></p>}{chosen&&!chosen.panelReceiver&&<Alert><AlertDescription>Este chat necesita recargar el plugin de fase 4 antes de iniciar desde el panel.</AlertDescription></Alert>}</CardContent></Card>
 {chosen&&<ProjectAuthorization key={owner+chosen.cwd} owner={owner} project={chosen.cwd} onError={onError}/>}
 <div className="mb-6 mt-8"><h2 className="mb-3 font-medium">¿Qué queréis hacer?</h2><div className="grid gap-3 sm:grid-cols-3">{presets.map(({id,title:name,description})=><button type="button" key={id} aria-pressed={mode===id} onClick={()=>setMode(id)} className={`rounded-lg border bg-card p-4 text-left ${mode===id?'border-primary ring-1 ring-primary':'hover:bg-muted'}`}><GitCompareArrows className="mb-3 size-5 text-primary"/><p className="text-sm font-medium">{name}</p><p className="mt-1 text-xs text-muted-foreground">{description}</p></button>)}</div></div>
 <ImplementationOptions codexRoot={chosen?.cwd??''} claudeRoot={other?.cwd??''} supported={!!chosen?.implementationReceiver} onChange={setImplementation}/>
 <Card className="mb-6"><CardHeader><CardTitle>Punto de partida</CardTitle><CardDescription>Podéis empezar ahora o continuar los análisis ya elaborados.</CardDescription></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2">{[{label:'Codex',start:startC,set:setStartC,text:analysisC,setText:setAnalysisC},{label:'Claude',start:startL,set:setStartL,text:analysisL,setText:setAnalysisL}].map(f=><div key={f.label} className="space-y-3"><Field label={f.label}><NativeSelect aria-label={`Punto de partida ${f.label}`} className="w-full" value={f.start} onChange={e=>f.set(e.target.value)}><NativeSelectOption value="new">Análisis nuevo</NativeSelectOption><NativeSelectOption value="existing">Usar análisis existente</NativeSelectOption></NativeSelect></Field>{f.start==='existing'&&<Textarea aria-label={`Análisis existente ${f.label}`} maxLength={32000} rows={5} value={f.text} onChange={e=>f.setText(e.target.value)} placeholder="Pega su análisis o una recapitulación atribuida…"/>}</div>)}<p className="text-xs text-muted-foreground sm:col-span-2">El puente comparte los textos aportados. No importa automáticamente el historial de las apps.</p></CardContent></Card>
 <div className="space-y-5"><Field label="Objetivo"><Textarea aria-label="Objetivo" required maxLength={16000} rows={4} value={objective} onChange={e=>setObjective(e.target.value)} placeholder="¿Qué queréis resolver? Describe la pregunta y el resultado que necesitas."/></Field><details className="rounded-lg border bg-card p-5"><summary className="cursor-pointer font-medium">Referencias y opciones</summary><div className="mt-5 space-y-5"><Field label="Restricciones" hint="Una por línea. Los permisos de las apps siguen aplicándose."><Textarea aria-label="Restricciones" rows={3} value={constraints} onChange={e=>setConstraints(e.target.value)}/></Field><Field label="Referencias" hint="Rutas, commits o enlaces, una referencia por línea."><Textarea aria-label="Referencias" rows={2} value={refs} onChange={e=>setRefs(e.target.value)}/></Field><div className="grid grid-cols-2 gap-4"><Field label="Máximo de mensajes"><Input aria-label="Máximo de mensajes" type="number" min={2} max={500} value={messages} onChange={e=>setMessages(Number(e.target.value))}/></Field><Field label="Tiempo máximo (minutos)"><Input aria-label="Tiempo máximo" type="number" min={1} max={1440} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></Field></div><div className="flex items-center justify-between gap-5"><div><Label htmlFor="barrier">Retener el intercambio inicial</Label><p className="mt-1 text-xs text-muted-foreground">Ambos registran su análisis antes de recibir el del otro. No garantiza independencia de su historial previo.</p></div><Switch id="barrier" checked={barrier&&startC==='new'&&startL==='new'} disabled={startC!=='new'||startL!=='new'} onCheckedChange={setBarrier}/></div><div className="flex items-center justify-between gap-5"><Label htmlFor="busy">Permitir Claude aunque esté ocupado</Label><Switch id="busy" checked={allowBusy} onCheckedChange={setAllowBusy}/></div></div></details></div>
 <div className="mt-7 flex flex-wrap items-center justify-between gap-3 border-t pt-6"><Button type="button" variant="outline" onClick={preflight} disabled={!valid||checkBusy}>{checkBusy?<Loader2 className="animate-spin"/>:verified?<Check/>:<RefreshCw/>}{verified?'Conexión comprobada':'Comprobar conexión'}</Button><Button type="submit" disabled={!valid||!verified||busy}>{busy?<Loader2 className="animate-spin"/>:<Play/>}Iniciar colaboración</Button></div><p className="mt-3 text-xs text-muted-foreground">La orden llegará al chat Codex seleccionado. Los agentes deciden cómo avanzar dentro de los límites.</p>
 </form>
}
function Conversation({run}:{run:Run}){
 const provider=(id:string)=>run.participants.find(p=>p.sessionId===id)?.provider??'Núcleo';
 const items=[...run.reports.map(r=>({key:r.id,at:r.created_at,title:r.report.title??(r.report.kind==='review'?'Revisión':'Aportación'),author:provider(r.author),text:r.body,status:r.report.verdict??'Declaración atribuida'})),...run.messages.filter(m=>!run.reports.some(r=>r.id===m.id)).map(m=>({key:m.id,at:m.created_at,title:m.direction==='out'?'Codex → Claude':'Claude → Codex',author:m.direction==='out'?'codex':'claude',text:m.contentRedacted?'Contenido retenido o no admitido.':m.text??'',status:m.status}))].sort((a,b)=>a.at-b.at);
 return items.length?<>{items.map(item=><Card key={item.key}><CardHeader className="pb-0"><div className="flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-sm font-medium"><span className={`size-2 rounded-full ${item.author==='codex'?'bg-primary':'bg-amber-500'}`}/>{item.author==='codex'?'Codex':'Claude'}</span><Badge variant="secondary">{item.status}</Badge></div><CardTitle className="text-sm">{item.title}</CardTitle></CardHeader><CardContent><Body text={item.text}/><p className="mt-3 text-xs text-muted-foreground">{date(item.at)}</p></CardContent></Card>)}</>:<Card><CardContent className="pt-6 text-muted-foreground">El objetivo está preparado. El chat Codex debe asignar y enviar el primer encargo.</CardContent></Card>;
}
function RunDetail({run,pending,control,onBack,onContinue}:{run:Run;pending:boolean;control:(action:string,text?:string,work?:Record<string,unknown>)=>Promise<boolean>;onBack:()=>void;onContinue:()=>void}){
 const [input,setInput]=useState('');const provider=(id:string)=>run.participants.find(p=>p.sessionId===id)?.provider??'Núcleo';const latest=run.results.filter(r=>!run.results.some(n=>n.report.resultId===r.report.resultId&&(n.report.version??0)>(r.report.version??0)));const final=run.closure?.result?run.results.find(r=>r.report.resultId===run.closure?.result?.resultId&&r.report.version===run.closure?.result?.version):latest.at(-1);const open=!terminal(run.state);
 return <><Button variant="ghost" className="mb-5 -ml-3" onClick={onBack}><ArrowLeft/>Colaboraciones</Button><div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div className="max-w-2xl"><div className="mb-3 flex flex-wrap gap-2"><State state={run.state}/><Badge variant="secondary">{phaseNames[run.coordination?.phase??'context']}</Badge><Badge variant="outline">Contexto {run.contextVersion}</Badge></div><h1 className="line-clamp-3 text-2xl font-semibold tracking-tight">{run.context.objective}</h1>{run.context.objective.length>180&&<details className="mt-2 text-sm text-muted-foreground"><summary className="cursor-pointer">Mostrar objetivo completo</summary><p className="prose-text mt-3">{run.context.objective}</p></details>}<p className="mt-2 text-xs text-muted-foreground">{date(run.createdAt)} · Codex + Claude</p></div><div className="flex gap-2">{open&&run.coordination&&<><Button variant="outline" disabled={pending} onClick={()=>void control(run.state==='active'?'pause':run.state==='recovery_required'?'recover':'resume')}>{run.state==='active'?<Pause/>:<Play/>}{run.state==='active'?'Pausar':run.state==='recovery_required'?'Recuperar':'Reanudar'}</Button><Button variant="outline" disabled={pending} onClick={()=>void control('cancel')}><Square/>Cancelar</Button></>}{!open&&<Button onClick={onContinue}>Continuar desde aquí<ArrowRight/></Button>}</div></div>
 {run.reason&&run.state!=='completed'&&<Alert className="mb-6"><AlertDescription>{reasonNames[run.reason]??run.reason}</AlertDescription></Alert>}{run.coordination?.initialBarrier&&!run.coordination.barrierOpen&&<Alert className="mb-6"><AlertDescription>El intercambio inicial está retenido hasta que ambos análisis estén registrados. El contenido del otro agente se mantiene oculto.</AlertDescription></Alert>}
 <div className="detail-grid grid grid-cols-[minmax(0,1fr)_270px] items-start gap-6"><div><Tabs defaultValue={terminal(run.state)?'result':'conversation'}><TabsList className="mb-5 h-auto flex-wrap"><TabsTrigger value="conversation">Intercambio</TabsTrigger><TabsTrigger value="result">Resultado</TabsTrigger><TabsTrigger value="activity">Actividad</TabsTrigger>{run.implementation&&<TabsTrigger value="implementation">Implementación</TabsTrigger>}</TabsList>
 <TabsContent value="conversation" className="space-y-4"><Conversation run={run}/>
 {open&&run.coordination&&<form className="rounded-lg border bg-card p-5" onSubmit={e=>{e.preventDefault();void control('input',input).then(ok=>{if(ok)setInput('')})}}><Label htmlFor="additional">Añadir una instrucción</Label><Textarea id="additional" className="mt-3" maxLength={4000} required rows={3} value={input} onChange={e=>setInput(e.target.value)} placeholder="Una precisión para continuar el trabajo…"/><div className="mt-3 flex items-center justify-between gap-3"><p className="text-xs text-muted-foreground">Creará una nueva versión del contexto.</p><Button size="sm" disabled={pending||!input.trim()} type="submit">Enviar<ArrowRight/></Button></div></form>}</TabsContent>
 <TabsContent value="result" className="space-y-5"><Card><CardHeader><p className="eyebrow">{run.closure?.disposition==='incomplete'||['cancelled','limit_reached'].includes(run.state)?'Resultado parcial':terminal(run.state)?'Salida de la colaboración':'Borrador vigente'}</p><CardTitle>{final?.report.title??(run.closure?.summary?'Resumen de cierre':open?'Aún no hay una propuesta registrada':'Sin resultado registrado')}</CardTitle><CardDescription>{final?`Autor: ${provider(final.author)} · versión ${final.report.version} · contexto ${final.contextVersion??1}`:open?'El resultado aparecerá cuando un agente lo registre.':'Esta colaboración se cerró sin resultado registrado. Consulta el intercambio o continúa desde aquí.'}</CardDescription></CardHeader><CardContent>{final&&<p className="prose-text leading-7">{final.body}</p>}{run.closure?.summary&&<p className="prose-text mt-5 text-muted-foreground">{run.closure.summary}</p>}{final&&<p className="mt-5 rounded-md bg-muted p-3 text-xs">{({none:'Esta versión no tiene revisión registrada.',self_only:'Solo tiene revisión del propio autor.',other_agent_current:'Hay una revisión del otro agente para esta versión.',other_agent_stale:'La revisión del otro agente corresponde a una versión anterior.'} as Record<string,string>)[final.reviewState]??'Consulta las revisiones atribuidas.'} Las evaluaciones expresan el criterio del agente; no certifican consenso.</p>}</CardContent></Card>
 {latest.length>1&&<details className="rounded-lg border p-4"><summary>Otras propuestas registradas ({latest.length-1})</summary>{latest.slice(0,-1).map(r=><article key={r.id} className="mt-4"><h3 className="font-medium">{r.report.title}</h3><p className="prose-text mt-2">{r.body}</p></article>)}</details>}
 <Card><CardHeader><CardTitle>Revisiones</CardTitle></CardHeader><CardContent className="space-y-4">{run.reviews.length===0?<p className="text-sm text-muted-foreground">Sin revisiones registradas.</p>:run.reviews.map(r=><div key={r.id} className="rounded-md border p-4"><div className="mb-2 flex flex-wrap items-center gap-2"><span className="font-medium">{provider(r.author)}</span><Badge variant="outline">{r.report.verdict}</Badge><span className="text-xs text-muted-foreground">v{r.report.version} · {r.current?'Vigente':'Versión anterior'}</span></div><p className="prose-text text-sm">{r.body}</p><details className="mt-3 text-xs text-muted-foreground"><summary>Versión revisada</summary><p className="mt-2 break-all">Hash: {r.targetHash}</p></details></div>)}</CardContent></Card>
 <Card><CardHeader><CardTitle>Desacuerdos y cuestiones abiertas</CardTitle></CardHeader><CardContent>{run.disagreements.length?run.disagreements.map((d,i)=><div key={d.reportId+':'+i} className="mb-3 border-l-2 border-amber-400 pl-4"><p className="text-xs text-muted-foreground">{provider(d.author)}</p><p className="prose-text mt-1 text-sm">{d.text}</p></div>):<p className="text-sm text-muted-foreground">No se han registrado desacuerdos. Eso por sí solo no acredita acuerdo.</p>}</CardContent></Card>
 <div className="flex gap-3"><Button variant="outline" asChild><a href={`/api/v1/runs/${run.id}/export?format=markdown`} download><Download/>Markdown</a></Button><Button variant="outline" asChild><a href={`/api/v1/runs/${run.id}/export?format=json`} download><Download/>JSON</a></Button></div></TabsContent>
 {run.implementation&&<TabsContent value="implementation"><ImplementationDetail runId={run.id} state={run.implementation} enabled={open&&run.state==='active'&&!pending&&!!run.coordination?.barrierOpen} onWork={work=>control('implementation',undefined,work)} inspect={()=>api('runs/'+run.id+'/implementation')}/></TabsContent>}
 <TabsContent value="activity"><Card><CardHeader><CardTitle>Cronología del núcleo</CardTitle><CardDescription>Eventos registrados, separados de las declaraciones de los agentes.</CardDescription></CardHeader><CardContent><ol className="space-y-5">{run.events.map(e=><li key={e.sequence} className="flex gap-3"><span className="mt-1.5 size-2 shrink-0 rounded-full bg-border"/><div><p className="text-sm">{e.type.replaceAll('_',' ')}</p><p className="mt-1 text-xs text-muted-foreground">{date(e.at)} · {provider(e.actor)}</p></div></li>)}</ol></CardContent></Card></TabsContent>
 </Tabs></div><aside className="space-y-5"><Card><CardHeader><CardTitle className="text-sm">Límites y progreso</CardTitle></CardHeader><CardContent className="space-y-4"><div><p className="mb-2 flex justify-between text-xs"><span className="text-muted-foreground">Mensajes admitidos</span><span>{run.messagesUsed} / {run.limits.maxMessages}</span></p><Progress value={Math.min(100,100*run.messagesUsed/run.limits.maxMessages)}/></div><div className="flex justify-between text-xs"><span className="text-muted-foreground">Tiempo máximo</span><span>{Math.round(run.limits.maxSeconds/60)} min</span></div><div className="flex justify-between text-xs"><span className="text-muted-foreground">Encargos pendientes</span><span>{run.pendingTasks.length}</span></div>{run.deadline&&open&&<p className="text-xs text-muted-foreground">Plazo: {date(run.deadline)}</p>}</CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Participantes</CardTitle></CardHeader><CardContent className="space-y-4">{run.participants.map(p=><div key={p.sessionId}><p className="text-xs font-medium uppercase">{p.provider}</p><p className="mt-1 break-words text-sm">{p.name}</p><details className="mt-1 text-xs text-muted-foreground"><summary>Proyecto</summary><p className="mt-1 break-all">{p.project.directory}</p></details></div>)}</CardContent></Card>{run.context.references.length>0&&<Card><CardHeader><CardTitle className="text-sm">Referencias</CardTitle></CardHeader><CardContent className="space-y-2">{run.context.references.map((r,i)=><p key={i} className="break-all text-xs text-muted-foreground">{r}</p>)}</CardContent></Card>}<p className="px-1 text-xs leading-5 text-muted-foreground">Pausar o cancelar detiene nuevas acciones del puente. No interrumpe herramientas que ya están ejecutándose en las apps.</p></aside></div></>
}
function Diagnostic({participants,bound,onError}:{participants:Participant[];bound:string|null;onError:(e:string)=>void}){
 const chats=participants.filter(p=>p.provider==='codex'&&(!bound||p.sessionId===bound));const [owner,setOwner]=useState(bound??chats[0]?.sessionId??''),[report,setReport]=useState<{checks:{code:string;level:string;message:string;remedy?:string}[]}|null>(null),[loading,setLoading]=useState(false);
 const check=async()=>{setLoading(true);try{setReport(await api('diagnostic',{ownerThread:owner,project:chats.find(c=>c.sessionId===owner)?.cwd}))}catch(e){onError((e as Error).message)}finally{setLoading(false)}};
 return <><p className="eyebrow mb-2">Conexión y compatibilidad</p><h1 className="text-3xl font-semibold tracking-tight">Diagnóstico</h1><p className="mb-8 mt-2 text-muted-foreground">Consulta el estado sin cambiar ajustes ni enviar mensajes.</p><Card><CardHeader><CardTitle>Revisar una conversación</CardTitle></CardHeader><CardContent><div className="flex flex-wrap gap-3"><NativeSelect aria-label="Chat para diagnóstico" value={owner} onChange={e=>setOwner(e.target.value)}>{chats.map(c=><NativeSelectOption key={c.sessionId} value={c.sessionId}>{participantLabel(c,participants)}</NativeSelectOption>)}</NativeSelect><Button disabled={!owner||loading} onClick={check}>{loading?<Loader2 className="animate-spin"/>:<RefreshCw/>}Comprobar</Button></div></CardContent></Card>{report&&<Card className="mt-6"><CardContent className="space-y-5 pt-6">{report.checks.map(c=><div key={c.code} className="flex gap-3"><span className={`mt-1.5 size-2 shrink-0 rounded-full ${c.level==='ok'?'bg-emerald-500':c.level==='blocked'?'bg-red-500':'bg-amber-500'}`}/><div><p className="text-sm font-medium">{c.level==='ok'?'Correcto':c.level==='blocked'?'Requiere atención':'No verificable automáticamente'} · {c.code.replaceAll('_',' ')}</p><p className="prose-text mt-1 text-sm text-muted-foreground">{c.message}</p>{c.remedy&&<p className="prose-text mt-2 text-xs text-muted-foreground">{c.remedy}</p>}</div></div>)}<Button variant="outline" onClick={()=>navigator.clipboard.writeText(JSON.stringify(report,null,2)).catch(e=>onError(e.message))}>Copiar diagnóstico</Button></CardContent></Card>}</>
}

type Authorization={project:string;enabled:boolean;revision:number;updatedAt:number|null;actor:string|null;folderChanged:boolean;chatPolicy:string;receiverSupported:boolean};
function ProjectAuthorization({owner,project,onError}:{owner:string;project:string;onError:(e:string)=>void}){
 const [state,setState]=useState<Authorization|null>(null),[confirm,setConfirm]=useState<number|null>(null),[busy,setBusy]=useState(false);
 const lock=useRef(false),request=useRef<{key:string;actionId:string}|null>(null);
 const path='project-authorization?'+new URLSearchParams({ownerThread:owner,project});
 useEffect(()=>{let active=true;const load=()=>api<Authorization>(path).then(s=>{if(active)setState(s)}).catch(e=>{if(active)onError(e.message)});void load();const timer=setInterval(()=>void load(),5000);return()=>{active=false;clearInterval(timer)}},[path,onError]);
 const change=async(enabled:boolean,expectedRevision=state?.revision)=>{
  if(!state||lock.current)return;lock.current=true;setBusy(true);
  const key=JSON.stringify({owner,project,enabled,revision:expectedRevision});if(request.current?.key!==key)request.current={key,actionId:crypto.randomUUID()};
  try {const result=await api<Authorization>('project-authorization',{ownerThread:owner,project,enabled,expectedRevision,actionId:request.current.actionId,confirmed:true});setState(result);setConfirm(null)}
  catch(e){onError((e as Error).message);try{setState(await api<Authorization>(path))}catch{}}finally{lock.current=false;setBusy(false)}
 };
 return <Card className="mt-6"><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><CardTitle>Autorización del proyecto</CardTitle><Badge variant={state?.enabled?'secondary':'outline'}>{state?state.enabled?'Recordada':'No recordada':'Consultando…'}</Badge></div><CardDescription>Recibir respuestas de Claude en los chats Codex de esta carpeta, incluidos los nuevos.</CardDescription></CardHeader><CardContent className="space-y-4">
 <p className="break-all rounded-md bg-muted p-3 text-xs">{state?.project??project}</p>
 <p className="text-sm text-muted-foreground">Solo respuestas verificadas de colaboraciones gestionadas en esta misma carpeta. Se conserva al reiniciar y puedes revocarla aquí. Los permisos de ejecución y edición siguen aplicándose; la recepción de Claude se configura en Claude.</p>
 {state&&<p className="text-xs text-muted-foreground">Ajuste propio de este chat: <strong>{({default:'predeterminado; puede heredar',accept:'aceptar; no depende de esta autorización',hold:'retener; tiene prioridad sobre el proyecto',refuse:'rechazar; tiene prioridad sobre el proyecto'} as Record<string,string>)[state.chatPolicy]??state.chatPolicy}</strong>.{state.updatedAt&&<> Última elección: {date(state.updatedAt)}.</>}</p>}
 {state&&!state.receiverSupported&&<Alert><AlertDescription>Este receptor necesita recargar el plugin actualizado para heredar la autorización. Puedes revocar una autorización existente.</AlertDescription></Alert>}
 {state?.folderChanged&&<Alert><AlertDescription>La carpeta ha cambiado de identidad. El permiso anterior no se hereda; confirma de nuevo para esta carpeta.</AlertDescription></Alert>}
 {confirm!==null&&!state?.enabled?<Alert><AlertDescription><p>¿Recordar la autorización para esta carpeta? Los chats Codex con recepción predeterminada podrán recibir futuras respuestas del participante Claude verificado en sus colaboraciones. Otros proyectos y mensajes retenidos anteriores quedan fuera.</p><div className="mt-4 flex flex-wrap gap-3"><Button type="button" disabled={busy} onClick={()=>void change(true,confirm)}>{busy&&<Loader2 className="animate-spin"/>}Confirmar autorización</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>setConfirm(null)}>Volver</Button></div></AlertDescription></Alert>:
 <Button type="button" variant={state?.enabled?'outline':'default'} disabled={!state||busy||!state.enabled&&!state.receiverSupported} onClick={()=>state?.enabled?void change(false):setConfirm(state!.revision)}>{busy?<Loader2 className="animate-spin"/>:<Check/>}{state?.enabled?'Revocar para este proyecto':'Recordar autorización para este proyecto'}</Button>}
 {state?.enabled&&<p className="text-xs text-muted-foreground">Revocar elimina la herencia. Si un chat tiene «aceptar» propio, debes cambiar ese ajuste en su bandeja de recepción.</p>}
 </CardContent></Card>
}
function AuthorizationPage({participants,bound,onError}:{participants:Participant[];bound:string|null;onError:(e:string)=>void}){
 const chats=participants.filter(p=>p.provider==='codex'&&(!bound||p.sessionId===bound));const [owner,setOwner]=useState(bound??chats[0]?.sessionId??'');const selected=chats.find(p=>p.sessionId===owner);
 return <div className="mx-auto max-w-3xl"><p className="eyebrow mb-2">Recepción de mensajes</p><h1 className="text-3xl font-semibold tracking-tight">Autorizaciones</h1><p className="mb-7 mt-2 text-muted-foreground">Decide qué proyecto puede recordar tu elección.</p><Field label="Conversación Codex"><NativeSelect aria-label="Chat para autorización" className="w-full" value={owner} onChange={e=>setOwner(e.target.value)}><NativeSelectOption value="">Seleccionar conversación</NativeSelectOption>{chats.map(p=><NativeSelectOption key={p.sessionId} value={p.sessionId}>{participantLabel(p,participants)}</NativeSelectOption>)}</NativeSelect></Field>{selected&&<ProjectAuthorization key={owner+selected.cwd} owner={owner} project={selected.cwd} onError={onError}/>}</div>
}
