import {useState,useRef} from 'react';
import {getLanguage} from './lib/i18n';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Badge} from '@/components/ui/badge';
const l=(en:string,es:string)=>getLanguage()==='es'?es:en;
type Peer={provider:string;sessionId:string;cwd:string;name:string;startedAt:number|null;symmetricDesktop:boolean};
type Ticket={id:string;project:string;targetProvider:string;adapter:string;state:string;revision:number;createdAt:number;bound:{sessionId:string}|null;reason:string|null};
type State={project:string;principal:{provider:string;sessionId:string};participants:Peer[];tickets:Ticket[];grants:{id:string;targetProvider:string;adapter:string;revokedAt:number|null;expiresAt:number|null}[];bindingErrors?:Record<string,string>};
type Api=<T>(path:string,body?:unknown)=>Promise<T>;
export function DesktopTickets({state,api,busy,act,onBound,onNotice}:{state:State;api:Api;busy:boolean;act:(fn:()=>Promise<void>)=>Promise<void>;onBound:(id:string,ticketId:string)=>void;onNotice:(text:string)=>void}){
 const other=state.principal.provider==='codex'?'claude':'codex',allowed=state.participants.filter(p=>p.cwd===state.project&&p.symmetricDesktop);
 const [adapter,setAdapter]=useState('manual'),[model,setModel]=useState(''),[executor,setExecutor]=useState(''),[remember,setRemember]=useState(false),[candidates,setCandidates]=useState<Record<string,string>>({});
 const request=useRef<{key:string;id:string;dispatch:string;grant:string;expiresAt:number}|null>(null),dispatches=useRef<Record<string,string>>({});
 const execute=(ticket:Ticket)=>act(async()=>{const executorId=executor||(ticket.adapter==='assisted_ui'?state.principal.sessionId:'');if(!executorId)throw new Error(l('Choose a live Codex executor.','Elige un chat Codex vivo como ejecutor.'));const commandId=dispatches.current[ticket.id]??=crypto.randomUUID();const job=await api<{state:string}>('desktop/creation_dispatch',{ticketId:ticket.id,executorId,commandId});onNotice(job.state==='unknown'?l('Creation wake is uncertain. Inspect the exact executor chat; it will not be repeated.','La activación para crear es incierta. Consulta el chat ejecutor exacto; no se repetirá.'):l('The exact executor was notified. Watch creation here; the new chat waits for binding before work starts.','Se ha avisado al ejecutor exacto. Consulta aquí la creación; el chat nuevo espera su vinculación antes de trabajar.'));});
 const create=()=>act(async()=>{const payload={targetProvider:other,project:state.project,mode:'local',adapter,ttlSeconds:600,...(model.trim()?{model:model.trim()}:{})},key=JSON.stringify({...payload,remember});if(request.current?.key!==key)request.current={key,id:crypto.randomUUID(),dispatch:crypto.randomUUID(),grant:crypto.randomUUID(),expiresAt:Date.now()+7*86400000};if(remember)await api('desktop/grants/create',{actionId:request.current.grant,project:state.project,targetProvider:other,adapter,mode:'local',actions:['create','bind'],expiresAt:request.current.expiresAt,maxActive:1,maxPerHour:3});const {ticket}=await api<{ticket:Ticket}>('desktop/tickets/request',{...payload,requestId:request.current.id});if(adapter!=='manual'){const executorId=executor||(adapter==='assisted_ui'?state.principal.sessionId:'');if(!executorId)throw new Error(l('Ticket saved. Choose a live Codex executor and dispatch below.','Solicitud guardada. Elige un chat Codex vivo y actívala debajo.'));dispatches.current[ticket.id]=request.current.dispatch;await api('desktop/creation_dispatch',{ticketId:ticket.id,executorId,commandId:request.current.dispatch});}onNotice(adapter==='manual'?l('Open a new local chat in the other app for this folder, then bind it below.','Abre un chat local nuevo en la otra app para esta carpeta y vincúlalo debajo.'):l('Authorized one creation. The executor uses the selected adapter and reports an outcome; uncertain creation is never repeated.','Una creación autorizada. El ejecutor usa el adaptador elegido y declara el resultado; una creación incierta nunca se repite.'));});
 return <div className="space-y-4"><p className="text-muted-foreground">{l('Open a new chat in the other app for this folder and link it here, or let it be created for you.','Abre un chat nuevo en la otra app para esta carpeta y vincúlalo aquí, o deja que se cree solo.')}</p>
 <div className="grid gap-3 sm:grid-cols-2"><div className="space-y-2"><Label>{l('Creation adapter','Adaptador de creación')}</Label><NativeSelect className="w-full" value={adapter} onChange={e=>setAdapter(e.target.value)}><NativeSelectOption value="manual">{l('Open manually','Abrir manualmente')}</NativeSelectOption>{other==='claude'?<NativeSelectOption value="assisted_ui">{l('Claude Desktop — assisted UI','Claude Desktop — UI asistida')}</NativeSelectOption>:<NativeSelectOption value="native_tool_relay">{l('Codex — official host tool relay','Codex — relevo con herramienta oficial')}</NativeSelectOption>}</NativeSelect></div><div className="space-y-2"><Label>{l('Requested model (optional)','Modelo solicitado (opcional)')}</Label><Input value={model} onChange={e=>setModel(e.target.value)} placeholder={other==='claude'?'Claude Opus 5.5':''}/></div></div>
 {adapter!=='manual'&&<><Label>{l('Exact creation executor','Ejecutor exacto de la creación')}</Label><NativeSelect className="w-full" value={executor} onChange={e=>setExecutor(e.target.value)}><NativeSelectOption value="">{adapter==='assisted_ui'?l('This Codex chat','Este chat Codex'):l('Choose a live Codex chat','Elige un chat Codex vivo')}</NativeSelectOption>{allowed.filter(p=>p.provider==='codex').map(p=><NativeSelectOption key={p.sessionId} value={p.sessionId}>{p.name} · {p.sessionId.slice(0,8)}</NativeSelectOption>)}</NativeSelect><p className="text-xs text-muted-foreground">{l('Assisted UI operates Claude Desktop only. It must not operate the bridge panel. Without a live Codex executor, open a new Codex chat manually.','La UI asistida opera solo Claude Desktop. No debe operar el panel del puente. Sin un ejecutor Codex vivo, abre un chat Codex nuevo manualmente.')}</p></>}
 <label className="flex gap-2 text-sm"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>{l('Remember creation + binding for this folder, provider and adapter for 7 days (1 active, 3/hour).','Recordar creación + vinculación en esta carpeta, proveedor y adaptador durante 7 días (1 activa, 3/hora).')}</label><Button disabled={busy} onClick={create}>{l('Authorize new conversation','Autorizar chat nuevo')}</Button>
 {(()=>{const finished=(t:Ticket)=>['expired','failed','cancelled'].includes(t.state)||(!!t.bound&&Date.now()-t.createdAt>86400000),ended=state.tickets.filter(finished);return <>{state.tickets.filter(t=>!finished(t)).map(t=><div className="space-y-3 rounded-md border p-3" key={t.id}><div className="flex justify-between gap-3"><span className="text-sm">{t.targetProvider} · {t.adapter} · {t.id.slice(0,8)}</span><Badge variant="outline">{t.state}</Badge></div>{state.bindingErrors?.[t.id]&&<p className="text-xs text-destructive">{state.bindingErrors[t.id]}</p>}{t.reason&&<p className="text-xs text-muted-foreground">{t.reason==='ttl'?l('Expired before it was used.','Caducó sin usarse.'):t.reason}</p>}{t.bound?<Button variant="outline" size="sm" onClick={()=>onBound(t.bound!.sessionId,t.id)}>{l('Use bound conversation','Usar chat vinculado')} · {t.bound.sessionId.slice(0,8)}</Button>:!['expired','failed','cancelled'].includes(t.state)&&<>
 {t.state==='requested'&&<Button size="sm" disabled={busy} onClick={()=>void act(async()=>{await api('desktop/tickets/authorize',{id:t.id,revision:t.revision})})}>{l('Authorize this ticket','Autorizar esta solicitud')}</Button>}
 {t.state==='authorized'&&t.adapter!=='manual'&&<Button size="sm" disabled={busy} onClick={()=>execute(t)}>{l('Notify exact executor','Avisar al ejecutor exacto')}</Button>}
 <p className="text-xs text-muted-foreground">{t.targetProvider==='codex'?l('Codex freshness is a receiver start time, not proof of a new chat. Verify the exact new chat yourself before binding.','La frescura de Codex es el inicio del receptor, no una prueba de chat nuevo. Comprueba tú el chat nuevo exacto antes de vincularlo.'):l('A matching host receipt can bind a new Claude chat. Otherwise choose and explicitly bind it.','Un recibo coincidente del host puede vincular un chat Claude nuevo. Si no, elígelo y vincúlalo explícitamente.')}</p>
 <NativeSelect className="w-full" value={candidates[t.id]??''} onChange={e=>setCandidates(c=>({...c,[t.id]:e.target.value}))}><NativeSelectOption value="">{l('Choose the exact new chat','Elige el chat nuevo exacto')}</NativeSelectOption>{state.participants.filter(p=>p.provider===t.targetProvider&&p.cwd===t.project&&p.startedAt!==null&&p.startedAt>=t.createdAt).map(p=><NativeSelectOption key={p.sessionId} value={p.sessionId}>{p.name} · {p.sessionId.slice(0,8)}</NativeSelectOption>)}</NativeSelect>
 <div className="flex flex-wrap gap-2"><Button size="sm" disabled={busy||!candidates[t.id]} onClick={()=>void act(async()=>{const bound=await api<Ticket>('desktop/tickets/bind',{id:t.id,sessionId:candidates[t.id]});onBound(bound.bound!.sessionId,t.id)})}>{l('Bind this chat','Vincular este chat')}</Button>{['awaiting_receiver','ambiguous','creation_uncertain'].includes(t.state)&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>void act(async()=>{const checked=await api<{ticket:Ticket;bindingError?:string}>('desktop/tickets/check',{id:t.id});if(checked.ticket.bound)onBound(checked.ticket.bound.sessionId,t.id);else onNotice(checked.bindingError??l('Waiting for a matching host receipt.','Esperando un recibo coincidente del host.'))})}>{l('Check host receipt','Comprobar recibo del host')}</Button>}<Button size="sm" variant="ghost" disabled={busy||t.state==='creating'} onClick={()=>void act(async()=>{await api('desktop/tickets/cancel',{id:t.id})})}>{l('Cancel','Cancelar')}</Button></div></> }</div>)}{ended.length>0&&<details className="text-xs text-muted-foreground"><summary className="cursor-pointer">{l('Earlier requests','Solicitudes anteriores')} ({ended.length})</summary><ul className="mt-2 space-y-1">{ended.map(t=><li key={t.id}>{t.targetProvider==='codex'?'Codex':'Claude'} · {new Date(t.createdAt).toLocaleString()} · {t.bound?l('bound','vinculada'):t.state==='expired'?l('expired','caducada'):t.state==='cancelled'?l('cancelled','cancelada'):l('failed','fallida')}</li>)}</ul></details>}</>})()}
 {state.grants.filter(g=>g.revokedAt===null).map(g=><div key={g.id} className="flex flex-wrap items-center justify-between gap-3 rounded-md border p-3 text-xs"><span>{l('Remembered creation','Creación recordada')} · {g.targetProvider} · {g.adapter}{g.expiresAt?' · '+new Date(g.expiresAt).toLocaleString():''}</span><Button variant="ghost" size="sm" disabled={busy} onClick={()=>void act(async()=>{await api('desktop/grants/revoke',{id:g.id})})}>{l('Revoke future creation','Revocar futuras creaciones')}</Button></div>)}
 </div>;
}
