import {useEffect,useRef,useState} from 'react';
import {getLanguage,useLanguage} from './lib/i18n';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Label} from '@/components/ui/label';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Badge} from '@/components/ui/badge';
import {Alert,AlertDescription} from '@/components/ui/alert';
import {Play,Pause,RefreshCw,Download,Plus,Check,ArrowLeft,ChevronRight} from 'lucide-react';
import {DesktopTickets} from './DesktopTickets';
import {serializedRefresh} from './lib/live-refresh';
import {State as RunState,providerName} from './RunState';

const l=(en:string,es:string)=>getLanguage()==='es'?es:en;
type Principal={provider:'codex'|'claude';sessionId:string};
type Peer=Principal&{name:string;cwd:string;status:string;symmetricDesktop:boolean;eligibleSurface:boolean;startedAt:number|null};
type Run={id:string;createdAt:number;initiator:Principal;state:string;reason:string|null;context:{objective:string;constraints:string[];references:string[];priorAnalysis:{codex?:string;claude?:string}};contextVersion:number;deadline:number|null;limits:{maxMessages:number|null;maxSeconds:number};messagesUsed:number;coordination:{revision:number;barrierOpen:boolean;structured:{structured:boolean;phase?:string;tasks?:{id:string;assignee:string;state:string;task:{intent:string}}[];closure?:{consensus:string;derivedReviewState:string;closure:{summary:string;disposition:string};disagreements:string[]}|null};lease:{epoch:number;expiresAt:number|null}};messages:{id:string;src:Principal;dst:Principal;text:string|null;status:string}[];reports:{id:string;author:string;body:string;report:{kind:string;version?:number;verdict?:string}}[];results:{author:string;report:{resultId:string;version:number;title:string}}[];implementation:{candidate:{contentHash:string;resultId:string;version:number}|null;checks:{name:string;exitCode:number;executedByCore:false}[];plan:{requiredChecks:string[]}}|null;reviews:{id:string;current:boolean;targetHash:string|null}[];validatedConsensus:false;consent:{valid:boolean;actor:string|null;expiresAt:number|null};preflight?:{readyForCheck:boolean;message:string};events?:{type:string;at:number}[]};
type Ticket={id:string;adapter:string;targetProvider:string;project:string;state:string;revision:number;correlationId:string|null;createdAt:number;expiresAt:number;bound:{sessionId:string}|null;reason:string|null};
type State={principal:Principal;project:string;runs:Run[];participants:Peer[];tickets:Ticket[];grants:{id:string;targetProvider:string;adapter:string;revokedAt:number|null;expiresAt:number|null}[];bindingErrors?:Record<string,string>};
type Api=<T>(path:string,body?:unknown)=>Promise<T>;
const needsApproval=(r:Run)=>r.state==='prepared'&&r.initiator.provider==='claude'&&!r.consent.valid;
const terminal=(state:string)=>['completed','cancelled','limit_reached'].includes(state);
const opened=(ms:number|null)=>ms?new Date(ms).toLocaleString(getLanguage(),{weekday:'short',hour:'2-digit',minute:'2-digit'}):'';
const ago=(ms:number)=>{const m=Math.round((Date.now()-ms)/60000);return m<1?l('just now','ahora'):m<60?l(`${m} min ago`,`hace ${m} min`):new Date(ms).toLocaleString(getLanguage(),{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})};
const delivery=():Record<string,string>=>({reserved:l('Queued','En cola'),submitting:l('Sending','Enviando'),'socket-written':l('Sent','Enviado'),started:l('Delivered','Entregado'),steered:l('Delivered','Entregado'),delivered:l('Delivered','Entregado'),consumed:l('Read','Leído'),held:l('Held by the other chat','Retenido por el otro chat'),denied:l('Denied','Denegado'),expired:l('Expired','Caducado'),unknown:l('Uncertain — not resent','Incierto — no se reenvía')});

export function DesktopCollaboration({api,onError,initialRun=''}:{api:Api;onError:(s:string)=>void;initialRun?:string}){
 useLanguage();
 const [state,setState]=useState<State|null>(null),[selected,setSelected]=useState(''),[composing,setComposing]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const refresh=useRef<()=>Promise<void>>(()=>Promise.resolve()),focused=useRef(false);
 useEffect(()=>{let alive=true;const worker=serializedRefresh(async()=>{try{const value=await api<State>('desktop/state');if(alive)setState(value)}catch(e){if(alive)onError((e as Error).message)}});refresh.current=worker.request;void worker.request();const timer=setInterval(()=>void worker.request(),2500),focus=()=>{if(document.visibilityState==='visible')void worker.request()};window.addEventListener('focus',focus);document.addEventListener('visibilitychange',focus);return()=>{alive=false;worker.stop();clearInterval(timer);window.removeEventListener('focus',focus);document.removeEventListener('visibilitychange',focus)}},[api,onError]);
 // A focus link opens on its run once; later selections are the human's.
 useEffect(()=>{if(focused.current||!state||!initialRun)return;focused.current=true;if(state.runs.some(r=>r.id===initialRun))setSelected(initialRun)},[state,initialRun]);
 useEffect(()=>{window.scrollTo({top:0})},[selected,composing]);
 const act=async(fn:()=>Promise<void>)=>{if(busy)return;setBusy(true);try{onError('');await fn();await refresh.current()}catch(e){onError((e as Error).message)}finally{setBusy(false)}};
 if(!state)return <p className="text-muted-foreground">{l('Loading…','Cargando…')}</p>;
 const run=state.runs.find(r=>r.id===selected),other=state.principal.provider==='codex'?'claude':'codex';
 const toast=notice&&<Alert role="status" className="fixed right-6 top-20 z-50 max-w-md bg-background shadow-lg"><AlertDescription className="flex justify-between gap-3">{notice}<button onClick={()=>setNotice('')} aria-label={l('Close','Cerrar')}>×</button></AlertDescription></Alert>;
 if(run)return <>{toast}<RunView run={run} api={api} busy={busy} act={act} onBack={()=>setSelected('')}/></>;
 const approvals=state.runs.filter(needsApproval),showComposer=composing||state.runs.length===0;
 return <div className="mx-auto max-w-3xl space-y-6">{toast}
  {approvals.map(r=><div key={r.id} className="rounded-xl border border-amber-300 bg-amber-50 p-5 dark:border-amber-800 dark:bg-amber-950"><p className="text-sm font-medium text-amber-900 dark:text-amber-200">{l('Waiting for your approval','Esperando tu aprobación')}</p><p className="mt-1 text-base">{r.context.objective}</p><div className="mt-4 flex gap-2"><Button disabled={busy} onClick={()=>void act(async()=>{await approveAndStart(api,r)})}><Play/>{l('Approve and start','Aprobar e iniciar')}</Button><Button variant="ghost" onClick={()=>setSelected(r.id)}>{l('See details','Ver detalles')}</Button></div></div>)}
  <div className="flex items-center justify-between gap-4"><h1 className="text-2xl font-semibold tracking-tight">{l('Collaborations','Colaboraciones')}</h1>{!showComposer&&<Button onClick={()=>setComposing(true)}><Plus/>{l('New','Nueva')}</Button>}</div>
  {showComposer&&<Composer state={state} other={other} api={api} busy={busy} act={act} onCancel={state.runs.length?()=>setComposing(false):undefined} onStarted={(id,text)=>{setComposing(false);setSelected(id);setNotice(text)}}/>}
  {state.runs.length>0&&<div className="overflow-hidden rounded-xl border bg-card">{state.runs.map(r=><button key={r.id} onClick={()=>setSelected(r.id)} className="flex w-full items-center gap-4 border-b px-5 py-4 text-left transition last:border-0 hover:bg-muted/60"><div className="min-w-0 flex-1"><p className="truncate font-medium">{r.context.objective}</p><p className="mt-0.5 text-xs text-muted-foreground">{providerName(r.initiator.provider)} ↔ {providerName(r.initiator.provider==='claude'?'codex':'claude')} · {r.messagesUsed}/{r.limits.maxMessages??'∞'} {l('messages','mensajes')} · {ago(r.createdAt)}</p></div>{needsApproval(r)?<Badge className="bg-amber-500 text-white">{l('Needs approval','Requiere aprobación')}</Badge>:<RunState state={r.state}/>}<ChevronRight className="size-4 text-muted-foreground"/></button>)}</div>}
 </div>;
}

async function approveAndStart(api:Api,run:Run,allowBusyPeer=false){
 if(run.initiator.provider==='claude'&&!run.consent.valid)await api('desktop/consent',{runId:run.id,expectedRevision:run.coordination.revision});
 await api('desktop/start',{runId:run.id,supervised:true,allowBusyPeer});
 return api<{state:string}>('desktop/notify',{runId:run.id,commandId:crypto.randomUUID()});
}

function Composer({state,other,api,busy,act,onCancel,onStarted}:{state:State;other:string;api:Api;busy:boolean;act:(fn:()=>Promise<void>)=>Promise<void>;onCancel?:()=>void;onStarted:(id:string,notice:string)=>void}){
 const peers=state.participants.filter(p=>p.provider===other&&p.cwd===state.project&&p.eligibleSurface),ready=peers.filter(p=>p.symmetricDesktop);
 const [peer,setPeer]=useState(''),[objective,setObjective]=useState(''),[messages,setMessages]=useState('24'),[minutes,setMinutes]=useState('30'),[busyPeer,setBusyPeer]=useState(false),[initialBarrier,setInitialBarrier]=useState(false),[priorCodex,setPriorCodex]=useState(''),[priorClaude,setPriorClaude]=useState(''),[implementation,setImplementation]=useState(''),[ticketId,setTicketId]=useState('');
 const request=useRef<{payload:string;id:string;notifyId:string}|null>(null);
 // With a single available chat there is nothing to choose.
 const chosen=peer||(ready.length===1?ready[0]!.sessionId:'');
 const start=()=>act(async()=>{if(!objective.trim()||!chosen)throw new Error(l('Choose a conversation and an objective.','Elige una conversación y un objetivo.'));const maxMessages=messages===''?null:Number(messages),maxSeconds=Number(minutes)*60;if(maxMessages!==null&&(!Number.isSafeInteger(maxMessages)||maxMessages<2)||!Number.isInteger(maxSeconds)||maxSeconds<60)throw new Error(l('Enter valid limits. Leave messages empty for no count limit.','Indica límites válidos. Deja mensajes vacío para no limitar su número.'));
  const payload={peerId:chosen,context:{objective:objective.trim(),constraints:[],references:[],priorAnalysis:{...(priorCodex.trim()?{codex:priorCodex}:{}),...(priorClaude.trim()?{claude:priorClaude}:{})}},limits:{maxMessages,maxSeconds},routine:{mode:'free'},...(initialBarrier?{coordination:{initialBarrier:true}}:{}),...(ticketId?{ticketId}:{}),...(implementation.trim()?{implementation:JSON.parse(implementation)}:{}),openPanel:false};
  const key=JSON.stringify(payload);if(request.current?.payload!==key)request.current={payload:key,id:crypto.randomUUID(),notifyId:crypto.randomUUID()};
  const prepared=await api<Run>('desktop/prepare',{...payload,requestId:request.current.id});
  // A human pressing start here is the approval itself for a Claude-initiated run.
  if(prepared.preflight&&!prepared.preflight.readyForCheck&&(prepared.initiator.provider!=='claude'||prepared.consent.valid)){onStarted(prepared.id,l('Prepared. Check the details before starting.','Preparada. Revisa los detalles antes de iniciarla.'));return;}
  if(prepared.initiator.provider==='claude'&&!prepared.consent.valid)await api('desktop/consent',{runId:prepared.id,expectedRevision:prepared.coordination.revision});
  await api('desktop/start',{runId:prepared.id,supervised:true,allowBusyPeer:busyPeer});
  const job=await api<{state:string}>('desktop/notify',{runId:prepared.id,commandId:request.current.notifyId});
  onStarted(prepared.id,job.state==='unknown'?l('Started, but the chat could not be woken for sure. Open it to check.','Iniciada, pero no se pudo confirmar el aviso al chat. Ábrelo para comprobarlo.'):l('Started. Both chats are working on it.','Iniciada. Los dos chats ya están en ello.'))});
 const peerName=providerName(other);
 return <div className="space-y-5 rounded-xl border bg-card p-6">
  {peers.length===0?<div className="rounded-lg bg-muted/60 p-4 text-sm"><p className="font-medium">{l(`No ${peerName} chat is open in this folder`,`No hay ningún chat de ${peerName} abierto en esta carpeta`)}</p><p className="mt-1 text-muted-foreground">{l(`Open one in ${peerName} Desktop and it will appear here.`,`Abre uno en ${peerName} Desktop y aparecerá aquí.`)}</p></div>
   :ready.length===1&&!peer?<p className="text-sm text-muted-foreground">{l('With','Con')} <strong className="text-foreground">{ready[0]!.name}</strong> · {l('opened','abierto')} {opened(ready[0]!.startedAt)}{peers.length>1&&<button className="ml-2 underline" onClick={()=>setPeer(ready[0]!.sessionId)}>{l('change','cambiar')}</button>}</p>
   :<div className="space-y-2"><Label>{l(`${peerName} chat`,`Chat de ${peerName}`)}</Label><NativeSelect className="w-full" value={chosen} onChange={e=>{setPeer(e.target.value);setTicketId('')}}><NativeSelectOption value="">{l('Choose…','Elige…')}</NativeSelectOption>{peers.map(p=><NativeSelectOption key={p.sessionId} value={p.sessionId} disabled={!p.symmetricDesktop}>{p.name}{p.startedAt?' · '+l('opened','abierto')+' '+opened(p.startedAt):''}{p.symmetricDesktop?(p.status==='busy'?' · '+l('busy','ocupado'):''):' · '+l('reload plugin','recarga el plugin')}</NativeSelectOption>)}</NativeSelect></div>}
  <div className="space-y-2"><Label htmlFor="objective">{l('What should they work on?','¿En qué tienen que trabajar?')}</Label><Textarea id="objective" value={objective} onChange={e=>setObjective(e.target.value)} rows={3} maxLength={16000} placeholder={l('E.g. Review the panel design together and propose improvements.','Ej.: Revisad juntos el diseño del panel y proponed mejoras.')}/></div>
  <details className="group text-sm"><summary className="cursor-pointer select-none text-muted-foreground">{l('More options','Más opciones')} · {messages||'∞'} {l('messages','mensajes')} · {minutes} min</summary><div className="mt-4 space-y-4">
   <div className="grid grid-cols-2 gap-4"><div className="space-y-1.5"><Label>{l('Max messages (empty = no limit)','Máx. mensajes (vacío = sin límite)')}</Label><Input type="number" min={2} value={messages} onChange={e=>setMessages(e.target.value)}/></div><div className="space-y-1.5"><Label>{l('Minutes','Minutos')}</Label><Input type="number" min={1} max={1440} value={minutes} onChange={e=>setMinutes(e.target.value)}/></div></div>
   <label className="flex gap-2"><input type="checkbox" checked={busyPeer} onChange={e=>setBusyPeer(e.target.checked)}/>{l('Start even if the other chat is busy','Empezar aunque el otro chat esté ocupado')}</label>
   <label className="flex gap-2"><input type="checkbox" checked={initialBarrier} onChange={e=>setInitialBarrier(e.target.checked)}/>{l('Each analyses first, then they compare','Que cada uno analice primero y luego comparen')}</label>
   <details><summary className="cursor-pointer text-muted-foreground">{l('Continue earlier analyses','Continuar análisis anteriores')}</summary><div className="mt-3 space-y-3"><Label>Codex</Label><Textarea value={priorCodex} onChange={e=>setPriorCodex(e.target.value)} maxLength={32000}/><Label>Claude</Label><Textarea value={priorClaude} onChange={e=>setPriorClaude(e.target.value)} maxLength={32000}/></div></details>
   <details><summary className="cursor-pointer text-muted-foreground">{l('Implementation contract (advanced)','Contrato de implementación (avanzado)')}</summary><p className="my-2 text-xs text-muted-foreground">{l('Clean Git base; separate files or worktrees; required checks. Grants no editing permission.','Base Git limpia; archivos o worktrees separados; comprobaciones obligatorias. No da permisos de edición.')}</p><Textarea className="font-mono text-xs" rows={8} value={implementation} onChange={e=>setImplementation(e.target.value)} placeholder={JSON.stringify({strategy:'files',workspaces:{codex:{root:state.project,paths:['src/a.ts']},claude:{root:state.project,paths:['src/b.ts']}},requiredChecks:['tests']},null,2)}/></details>
  </div></details>
  <div className="flex items-center gap-2"><Button disabled={busy||!chosen||!objective.trim()} onClick={start}><Play/>{l('Start','Empezar')}</Button>{onCancel&&<Button variant="ghost" onClick={onCancel}>{l('Cancel','Cancelar')}</Button>}</div>
  <details className="border-t pt-4 text-sm" open={peers.length===0||state.tickets.some(t=>!['expired','failed','cancelled'].includes(t.state)&&!t.bound)}><summary className="cursor-pointer select-none text-muted-foreground">{l(`Need a new ${peerName} chat?`,`¿Necesitas un chat nuevo de ${peerName}?`)}</summary><div className="mt-4"><DesktopTickets state={state} api={api} busy={busy} act={act} onBound={(id,ticket)=>{setPeer(id);setTicketId(ticket)}} onNotice={()=>{}}/></div></details>
 </div>;
}

function RunView({run,api,busy,act,onBack}:{run:Run;api:Api;busy:boolean;act:(fn:()=>Promise<void>)=>Promise<void>;onBack:()=>void}){
 const [closing,setClosing]=useState(false),[summary,setSummary]=useState(''),[disposition,setDisposition]=useState('proposal'),[inspection,setInspection]=useState<{hash:string;ready:boolean;reasons:string[]}|null>(null);
 const control=(action:string,extra:Record<string,unknown>={})=>act(async()=>{await api('desktop/control',{runId:run.id,commandId:crypto.randomUUID(),expectedRevision:run.coordination.revision,control:{action,...extra}})});
 const finish=()=>control('finish',{closure:{summary:summary.trim()||l('Closed from the panel without a final proposal.','Cerrada desde el panel sin propuesta final.'),disposition:summary.trim()?disposition:'incomplete'}}).then(()=>setClosing(false));
 const exportRun=()=>act(async()=>{const value=await api<{content:string}>('desktop/export',{runId:run.id,format:'markdown'});const url=URL.createObjectURL(new Blob([value.content],{type:'text/markdown'})),a=document.createElement('a');a.href=url;a.download=`desktop-${run.id}.md`;a.click();URL.revokeObjectURL(url)});
 const inFlight=run.messages.some(m=>['reserved','submitting','unknown'].includes(m.status)),leaseLive=run.state==='active'&&!!run.coordination.lease.expiresAt&&run.coordination.lease.expiresAt>Date.now();
 const closure=run.coordination.structured.closure,moves=(run.events??[]).filter(e=>e.type==='project_revision_moved');
 return <div className="mx-auto max-w-3xl space-y-6">
  <button onClick={onBack} className="flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4"/>{l('All collaborations','Todas las colaboraciones')}</button>
  <div className="space-y-3"><div className="flex items-start justify-between gap-4"><h1 className="text-xl font-semibold leading-snug">{run.context.objective}</h1>{needsApproval(run)?<Badge className="bg-amber-500 text-white">{l('Needs approval','Requiere aprobación')}</Badge>:<RunState state={run.state}/>}</div>
   <p className="text-sm text-muted-foreground">{providerName(run.initiator.provider)} ↔ {providerName(run.initiator.provider==='claude'?'codex':'claude')} · {run.messagesUsed}/{run.limits.maxMessages??'∞'} {l('messages','mensajes')}{run.deadline&&!terminal(run.state)?' · '+l('ends at','termina a las')+' '+new Date(run.deadline).toLocaleTimeString(getLanguage(),{hour:'2-digit',minute:'2-digit'}):''}</p>
   <div className="flex flex-wrap items-center gap-2">
    {run.state==='prepared'&&<Button disabled={busy} onClick={()=>void act(async()=>{await approveAndStart(api,run)})}><Play/>{needsApproval(run)?l('Approve and start','Aprobar e iniciar'):l('Start','Iniciar')}</Button>}
    {run.state==='active'&&<Button variant="outline" disabled={busy} onClick={()=>void control('pause')}><Pause/>{l('Pause','Pausar')}</Button>}
    {run.state==='paused'&&<Button disabled={busy||inFlight} onClick={()=>void control('resume')}><Play/>{l('Resume','Reanudar')}</Button>}
    {['active','paused','blocked','recovery_required'].includes(run.state)&&!leaseLive&&run.state!=='paused'&&<Button variant="outline" disabled={busy} onClick={()=>void control('recover')}><RefreshCw/>{l('Recover','Recuperar')}</Button>}
    {!terminal(run.state)&&run.state!=='prepared'&&<Button variant="outline" disabled={busy} onClick={()=>setClosing(!closing)}><Check/>{l('Finish','Finalizar')}</Button>}
    {!terminal(run.state)&&<Button variant="ghost" disabled={busy} onClick={()=>void control('cancel')}>{run.state==='prepared'?l('Discard','Descartar'):l('Cancel','Cancelar')}</Button>}
    <Button variant="ghost" size="sm" disabled={busy} onClick={()=>void exportRun()}><Download/>{l('Export','Exportar')}</Button>
   </div>
   {closing&&<div className="space-y-3 rounded-lg border p-4"><Label htmlFor="closing">{l('Outcome (optional)','Resultado (opcional)')}</Label><Textarea id="closing" rows={3} maxLength={4000} value={summary} onChange={e=>setSummary(e.target.value)} placeholder={l('What did they conclude?','¿A qué conclusión llegaron?')}/><div className="flex flex-wrap items-center gap-2"><NativeSelect size="sm" value={disposition} onChange={e=>setDisposition(e.target.value)}><NativeSelectOption value="proposal">{l('Proposal','Propuesta')}</NativeSelectOption><NativeSelectOption value="with_disagreements">{l('With disagreements','Con desacuerdos')}</NativeSelectOption><NativeSelectOption value="incomplete">{l('Incomplete','Incompleta')}</NativeSelectOption></NativeSelect><Button size="sm" disabled={busy} onClick={()=>void finish()}>{l('Finish','Finalizar')}</Button></div></div>}
  </div>
  {closure&&<div className="rounded-xl bg-muted p-5"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{l('Outcome','Resultado')} · {({proposal:l('Proposal','Propuesta'),with_disagreements:l('With disagreements','Con desacuerdos'),incomplete:l('Incomplete','Incompleta')} as Record<string,string>)[closure.closure.disposition]??closure.closure.disposition}</p><p className="mt-2 whitespace-pre-wrap">{closure.closure.summary}</p>{closure.disagreements.map((text,i)=><p className="mt-2 text-sm text-muted-foreground" key={i}>• {text}</p>)}</div>}
  {run.reason&&!closure&&!['finish','cancel'].includes(run.reason)&&<p className="text-sm text-muted-foreground">{run.reason}</p>}
  {moves.length>0&&<p className="text-sm text-muted-foreground">{l(`The folder changed outside this collaboration ${moves.length===1?'once':moves.length+' times'} (last ${ago(moves.at(-1)!.at)}). It kept going; the chats were told with the next message.`,`La carpeta cambió fuera de esta colaboración ${moves.length===1?'una vez':moves.length+' veces'} (la última ${ago(moves.at(-1)!.at)}). Siguió adelante; se avisó a los chats en el siguiente mensaje.`)}</p>}
  {run.coordination.structured.structured&&<p className="text-sm text-muted-foreground">{run.coordination.barrierOpen?l('Both analyses are in; they can compare now.','Los dos análisis están listos; ya pueden comparar.'):l('Waiting for both independent analyses.','Esperando los dos análisis independientes.')}</p>}
  {run.implementation&&<div className="space-y-2 rounded-xl border p-4 text-sm"><div className="flex items-center justify-between gap-3"><p className="font-medium">{l('Implementation','Implementación')}</p><Button variant="outline" size="sm" disabled={busy} onClick={()=>void act(async()=>{const value=await api<{ready:boolean;reasons:string[];candidate:{contentHash:string}|null}>('desktop/implementation',{runId:run.id,operationId:crypto.randomUUID(),action:{action:'inspect'}});setInspection({hash:value.candidate?.contentHash??'',ready:value.ready,reasons:value.reasons})})}>{l('Check readiness','Comprobar si está lista')}</Button></div><p className="text-muted-foreground">{run.implementation.candidate?`${l('Version','Versión')} ${run.implementation.candidate.version}`:l('No candidate yet','Todavía no hay candidato')}{run.implementation.checks.length?' · '+run.implementation.checks.map(c=>`${c.name} ${c.exitCode===0?'✓':'✗'}`).join(' · '):''}</p>{inspection&&inspection.hash===run.implementation.candidate?.contentHash&&<div><p>{inspection.ready?l('Ready to integrate right now.','Lista para integrar ahora mismo.'):l('Not ready yet:','Todavía no está lista:')}</p><ul className="mt-1 list-disc pl-5 text-muted-foreground">{inspection.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul></div>}</div>}
  <div className="space-y-3">{run.messages.length===0&&!closure&&<p className="py-8 text-center text-sm text-muted-foreground">{terminal(run.state)?l('No messages were sent.','No se envió ningún mensaje.'):run.state==='prepared'?l('Nothing has been sent yet.','Todavía no se ha enviado nada.'):l('Waiting for the first message…','Esperando el primer mensaje…')}</p>}
   {run.messages.map(m=>{const mine=m.src.provider===run.initiator.provider;return <div key={m.id} className={`flex ${mine?'justify-start':'justify-end'}`}><div className={`max-w-[85%] rounded-2xl px-4 py-3 ${mine?'rounded-tl-sm bg-card border':'rounded-tr-sm bg-primary/10'}`}><p className="mb-1 text-xs text-muted-foreground"><strong className="text-foreground">{providerName(m.src.provider)}</strong> · {delivery()[m.status]??m.status}</p><p className="whitespace-pre-wrap break-words text-sm">{m.text??l('Content withheld until both analyses are in','Contenido retenido hasta tener ambos análisis')}</p></div></div>})}
   {run.reports.map(r=><div key={r.id} className="rounded-xl border-l-4 border-primary bg-card p-4"><p className="mb-1 text-xs text-muted-foreground"><strong className="text-foreground">{r.author.startsWith('codex')?'Codex':r.author.startsWith('claude')?'Claude':r.author}</strong> · {({response:l('Report','Informe'),result:l('Result','Resultado'),review:l('Review','Revisión')} as Record<string,string>)[r.report.kind]??r.report.kind}{r.report.version?` v${r.report.version}`:''}{r.report.verdict?' · '+(({agree:l('agrees','de acuerdo'),revise:l('asks for changes','pide cambios'),disagree:l('disagrees','en desacuerdo')} as Record<string,string>)[r.report.verdict]??r.report.verdict):''}</p><p className="whitespace-pre-wrap text-sm">{r.body}</p></div>)}
  </div>
 </div>;
}
