import { Database } from 'bun:sqlite';
import { chmodSync, existsSync, lstatSync, mkdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { createHash, randomBytes, randomUUID } from 'node:crypto';
import { z } from 'zod';
import { privateDirectory, uuid } from './claude';
import { contextSchema, RunStore } from './runs';
import { reportSchema, taskSchema, normalizeRoutine, type Report, type Task, type RoutineInput, type Closure } from './routines';
import type { Participant } from './participants';
import {DesktopCoordination,type DesktopPhase} from './desktop-coordination';
import {DesktopImplementation} from './desktop-implementation';

export type Principal = {provider:'codex'|'claude';sessionId:string};
export const principalSchema=z.object({provider:z.enum(['codex','claude']),sessionId:uuid}).strict();
export const desktopLimitsSchema=z.object({maxMessages:z.number().int().min(2).max(1000000).nullable().default(24),maxSeconds:z.number().int().min(1).max(86400).default(1800)}).strict();
export const desktopPrefix='CC_CDX_DESKTOP_V2 ';
export const desktopHeaderSchema=z.object({runId:uuid,messageId:uuid,capability:z.string().regex(/^[a-f0-9]{64}$/),contextVersion:z.number().int().positive(),replyTo:uuid.optional()}).strict();
type Header=z.infer<typeof desktopHeaderSchema>;
type RunRow={id:string;initiator:string;request_id:string;request_hash:string;state:string;context:string;context_version:number;routine:string;limits:string;participants:string;deadline:number|null;messages_used:number;revision:number;lease_holder:string|null;lease_epoch:number;lease_until:number|null;created_at:number;reason:string|null};
type MessageRow={id:string;run_id:string;src:string;dst:string;context_version:number;body:string;request_hash:string;cap_hash:string;status:string;epoch:number;transport_id:string|null;reply_to:string|null;task:string|null;delivery_claimed:number;created_at:number;authorized:number};
const hash=(v:unknown)=>createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex');
const key=(p:Principal)=>p.provider+':'+uuid.parse(p.sessionId);
const same=(a:Principal,b:Principal)=>key(a)===key(b);

/** Additive namespace in the existing private database. Legacy IDs, logs and
 * grants remain byte-for-byte records; legacy writers cannot steal new claims.
 * This is local same-UID attribution, not protection from a compromised UID. */
export class DesktopRunStore {
  readonly db:Database;
  readonly coordination:DesktopCoordination;
  constructor(readonly stateDir:string,private now=()=>Date.now()){
    mkdirSync(stateDir,{recursive:true,mode:0o700});privateDirectory(stateDir);
    const path=join(stateDir,'collaborations.sqlite');
    if(!existsSync(path)){const legacy=new RunStore(stateDir,now);legacy.close();}
    const st=lstatSync(path);if(!st.isFile()||st.isSymbolicLink()||st.uid!==process.getuid?.()||(st.mode&0o077))throw new Error('Desktop state must be a private owned file');
    this.db=new Database(path,{strict:true});chmodSync(path,0o600);
    this.db.exec('PRAGMA busy_timeout=5000; PRAGMA foreign_keys=ON;');
    this.db.transaction(()=>this.db.exec(`
      CREATE TABLE IF NOT EXISTS desktop_runs(id TEXT PRIMARY KEY,initiator TEXT NOT NULL,request_id TEXT NOT NULL UNIQUE,request_hash TEXT NOT NULL,state TEXT NOT NULL,context TEXT NOT NULL,context_version INTEGER NOT NULL,routine TEXT NOT NULL,limits TEXT NOT NULL,participants TEXT NOT NULL,deadline INTEGER,messages_used INTEGER NOT NULL,revision INTEGER NOT NULL,lease_holder TEXT,lease_epoch INTEGER NOT NULL,lease_until INTEGER,created_at INTEGER NOT NULL,reason TEXT);
      CREATE TABLE IF NOT EXISTS desktop_claims(session_id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES desktop_runs(id));
      CREATE TABLE IF NOT EXISTS desktop_messages(id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES desktop_runs(id),src TEXT NOT NULL,dst TEXT NOT NULL,context_version INTEGER NOT NULL,body TEXT NOT NULL,request_hash TEXT NOT NULL,cap_hash TEXT NOT NULL,status TEXT NOT NULL,epoch INTEGER NOT NULL,transport_id TEXT UNIQUE,reply_to TEXT,task TEXT,delivery_claimed INTEGER NOT NULL,created_at INTEGER NOT NULL,authorized INTEGER NOT NULL DEFAULT 0);
      CREATE TABLE IF NOT EXISTS desktop_run_consents(run_id TEXT PRIMARY KEY,consent_hash TEXT NOT NULL,panel_session TEXT NOT NULL,created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,used_bootstrap_message_id TEXT,revoked_at INTEGER);
      CREATE TABLE IF NOT EXISTS desktop_bootstraps(run_id TEXT PRIMARY KEY,message_id TEXT NOT NULL UNIQUE);
      CREATE TABLE IF NOT EXISTS desktop_executors(holder TEXT PRIMARY KEY,pid INTEGER NOT NULL,proc_start TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS desktop_wires(message_id TEXT PRIMARY KEY,wire_hash TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS desktop_deliveries(transport_id TEXT PRIMARY KEY,input_id TEXT NOT NULL,consumed_at INTEGER);
      CREATE TABLE IF NOT EXISTS desktop_reports(id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES desktop_runs(id),author TEXT NOT NULL,context_version INTEGER NOT NULL,payload TEXT NOT NULL,body TEXT NOT NULL,content_hash TEXT NOT NULL,created_at INTEGER NOT NULL);
      CREATE TABLE IF NOT EXISTS desktop_contexts(run_id TEXT NOT NULL,version INTEGER NOT NULL,body TEXT NOT NULL,PRIMARY KEY(run_id,version));
      CREATE TABLE IF NOT EXISTS desktop_actions(id TEXT PRIMARY KEY,run_id TEXT NOT NULL,request_hash TEXT NOT NULL,result TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS desktop_events(sequence INTEGER PRIMARY KEY AUTOINCREMENT,run_id TEXT NOT NULL,type TEXT NOT NULL,actor TEXT NOT NULL,at INTEGER NOT NULL,payload TEXT NOT NULL);
      CREATE TRIGGER IF NOT EXISTS desktop_claim_blocks_legacy BEFORE INSERT ON session_claims WHEN EXISTS(SELECT 1 FROM desktop_claims WHERE session_id=NEW.session_id) BEGIN SELECT RAISE(ABORT,'Session belongs to a Desktop collaboration'); END;
    `)).immediate();
    DesktopCoordination.install(this.db);this.coordination=new DesktopCoordination(this.db,now);
  }
  close(){this.db.close();}
  implementationPlan(id:string){DesktopImplementation.install(this.db);return new DesktopImplementation(this.db).plan(id);}
  authorizeIncoming(transportId:string){const m=this.byTransport(transportId);if(!m)return null;const r=this.expire(m.run_id);if(r.state==='paused')return 'buffer' as const;return r.state==='active'&&m.authorized&&m.context_version===r.context_version&&m.epoch===r.lease_epoch?'deliver' as const:'drop' as const;}
  private consentHash(r:RunRow){return hash({initiator:r.initiator,participants:(JSON.parse(r.participants) as Participant[]).map(p=>{const st=statSync(p.project.directory,{bigint:true});return {provider:p.provider,sessionId:p.sessionId,pid:p.pid,procStart:p.procStart,project:p.project,dev:String(st.dev),ino:String(st.ino)}}),contextVersion:r.context_version,context:r.context,limits:r.limits,routine:r.routine});}
  consent(id:string,p:Principal,panelActor:string,expectedRevision:number){return this.db.transaction(()=>{const r=this.expire(id);this.member(r,p);if(!panelActor.startsWith('panel_session:'))throw new Error('Only the panel may authorize a run');if(r.revision!==expectedRevision||!['prepared','paused','active'].includes(r.state))throw new Error('Run changed; inspect its exact scope before consenting');if(!r.initiator.startsWith('claude:'))throw new Error('Run consent is for Claude initiation only');this.db.run('INSERT INTO desktop_run_consents VALUES(?,?,?,?,?,NULL,NULL) ON CONFLICT(run_id) DO UPDATE SET consent_hash=excluded.consent_hash,panel_session=excluded.panel_session,created_at=excluded.created_at,expires_at=excluded.expires_at,revoked_at=NULL',[id,this.consentHash(r),panelActor,this.now(),r.deadline??this.now()+600000]);this.event(id,'run_consent',panelActor,{contextVersion:r.context_version,scope:'this_run_only',humanPresenceVerified:false});return this.consentStatus(id);}).immediate();}
  consentStatus(id:string){const r=this.expire(id),c=this.db.query<{consent_hash:string;panel_session:string;expires_at:number;used_bootstrap_message_id:string|null;revoked_at:number|null},[string]>('SELECT * FROM desktop_run_consents WHERE run_id=?').get(id);let matches=false;try{matches=!!c&&c.consent_hash===this.consentHash(r)}catch{}return {valid:matches&&!!c&&c.revoked_at===null&&c.expires_at>this.now()&&!['completed','cancelled','limit_reached'].includes(r.state),expiresAt:c?.expires_at??null,actor:c?.panel_session??null,bootstrapMessageId:c?.used_bootstrap_message_id??null};}
  revokeConsent(id:string,p:Principal,panelActor:string){this.member(this.row(id),p);if(!panelActor.startsWith('panel_session:'))throw new Error('Only the panel may revoke consent');this.db.run('UPDATE desktop_run_consents SET revoked_at=? WHERE run_id=?',[this.now(),id]);this.event(id,'run_consent_revoked',panelActor,{});return this.consentStatus(id);}
  consentAllows(transportId:string,receiver:Principal,project:string){const m=this.byTransport(transportId);if(!m||m.dst!==key(receiver)||!m.authorized)return false;const r=this.expire(m.run_id);return r.initiator===m.src&&r.initiator.startsWith('claude:')&&(JSON.parse(r.participants) as Participant[]).every(p=>p.project.directory===project)&&this.consentStatus(r.id).valid;}
  registerExecutor(holder:string,pid:number,procStart:string){this.db.run('INSERT INTO desktop_executors VALUES(?,?,?)',[holder,pid,procStart]);}
  heartbeat(holder:string){this.db.run("UPDATE desktop_runs SET lease_until=? WHERE lease_holder=? AND lease_until>? AND state IN('active','paused','blocked')",[this.now()+300000,holder,this.now()]);}
  private executorAlive(holder:string|null){if(!holder)return false;const e=this.db.query<{pid:number;proc_start:string},[string]>('SELECT * FROM desktop_executors WHERE holder=?').get(holder);if(!e)return false;const ps=Bun.spawnSync(['ps','-o','lstart=','-p',String(e.pid)],{env:{...process.env,LC_ALL:'C',TZ:'UTC'},stdout:'pipe',stderr:'ignore'});return ps.exitCode===0&&ps.stdout.toString().trim()===e.proc_start;}
  incomingParticipants(transportId:string){const m=this.byTransport(transportId);return m?{runId:m.run_id,participants:JSON.parse(this.row(m.run_id).participants) as Participant[]}:null;}
  activeFor(p:Principal){const claim=this.db.query<{run_id:string},[string]>('SELECT run_id FROM desktop_claims WHERE session_id=?').get(p.sessionId);if(!claim)return null;const r=this.expire(claim.run_id);return ['active','paused','blocked'].includes(r.state)?r.id:null;}
  projectAuthorizationCandidate(transportId:string,receiver:Principal,project:string){const m=this.byTransport(transportId);if(!m||m.dst!==key(receiver)||!m.authorized||!m.reply_to)return null;const r=this.expire(m.run_id);if(r.initiator!==key(receiver)||r.context_version!==m.context_version||!['active','paused'].includes(r.state))return null;const participants=JSON.parse(r.participants) as Participant[];if(participants.some(p=>p.project.directory!==project))return null;const parent=this.message(m.reply_to);if(!parent||parent.run_id!==r.id||parent.src!==key(receiver)||parent.dst!==m.src||parent.context_version!==r.context_version)return null;return {receivedAt:m.created_at};}
  private row(id:string){const r=this.db.query<RunRow,[string]>('SELECT * FROM desktop_runs WHERE id=?').get(uuid.parse(id));if(!r)throw new Error('Desktop collaboration does not exist');return r;}
  private event(id:string,type:string,actor:string,payload:unknown){this.db.run('INSERT INTO desktop_events(run_id,type,actor,at,payload) VALUES(?,?,?,?,?)',[id,type,actor,this.now(),JSON.stringify(payload)]);}
  private expire(id:string){const r=this.row(id);if(!['completed','cancelled','limit_reached','prepared'].includes(r.state)&&r.deadline!==null&&this.now()>=r.deadline)this.terminal(id,'limit_reached','deadline','core');return this.row(id);}
  private terminal(id:string,state:string,reason:string,actor:string){this.db.run('UPDATE desktop_runs SET state=?,reason=?,revision=revision+1 WHERE id=?',[state,reason,id]);this.db.run('DELETE FROM desktop_claims WHERE run_id=?',[id]);this.event(id,state,actor,{reason});}
  private member(r:RunRow,p:Principal){if(!(JSON.parse(r.participants) as Participant[]).some(x=>same({provider:x.provider,sessionId:x.sessionId},p)))throw new Error('Caller is not a participant');}
  private owner(r:RunRow,p:Principal){if(r.initiator!==key(p))throw new Error('Only the initiating participant can control this collaboration');}
  prepare(p:Principal,requestId:string,context:unknown,limits:unknown,participants:Participant[],routine?:RoutineInput,actor?:string,extensions?:unknown){
    principalSchema.parse({provider:p.provider,sessionId:p.sessionId});uuid.parse(requestId);const c=contextSchema.parse(context),l=desktopLimitsSchema.parse(limits),orientation=normalizeRoutine(routine,c.priorAnalysis);
    if(participants.length!==2||new Set(participants.map(x=>x.provider)).size!==2||!participants.some(x=>same(p,x)))throw new Error('Select one exact Codex and one exact Claude Desktop participant');
    const payload={p,c,l,participants:participants.map(x=>({...x,status:undefined,name:undefined})),orientation,extensions},digest=hash(payload);
    return this.db.transaction(()=>{const old=this.db.query<RunRow,[string]>('SELECT * FROM desktop_runs WHERE request_id=?').get(requestId);if(old){if(old.request_hash!==digest)throw new Error('Request ID reused with different content');return old.id;}
      const id=randomUUID();this.db.run("INSERT INTO desktop_runs VALUES(?,?,?,?,? ,?,1,?,?,?,NULL,0,0,NULL,0,NULL,?,NULL)",[id,key(p),requestId,digest,'prepared',JSON.stringify(c),JSON.stringify(orientation),JSON.stringify(l),JSON.stringify(participants),this.now()]);
      this.db.run('INSERT INTO desktop_contexts VALUES(?,1,?)',[id,JSON.stringify(c)]);this.event(id,'prepared',actor??key(p),{schema:'desktop_v2',authority:'local_same_uid'});return id;
    }).immediate();
  }
  start(id:string,p:Principal,holder:string,actor?:string){return this.db.transaction(()=>{const r=this.expire(id);if(actor){if(!actor.startsWith('panel_session:'))throw new Error('Only a scoped panel may start as a participant');this.member(r,p);}else this.owner(r,p);if(!this.executorAlive(holder))throw new Error('Executor process is not registered or alive');if(r.state==='active')return r.lease_epoch;if(r.state!=='prepared')throw new Error('Cannot start '+r.state);
    for(const participant of JSON.parse(r.participants) as Participant[]){const claimed=this.db.query<{run_id:string},[string]>('SELECT run_id FROM desktop_claims WHERE session_id=?').get(participant.sessionId);if(claimed){this.expire(claimed.run_id);if(this.db.query('SELECT 1 FROM desktop_claims WHERE session_id=?').get(participant.sessionId))throw new Error('Conversation already participates in another Desktop collaboration');}const legacy=this.db.query<{run_id:string},[string]>('SELECT run_id FROM session_claims WHERE session_id=?').get(participant.sessionId);if(legacy)throw new Error('Participant has an active legacy collaboration');this.db.run('INSERT INTO desktop_claims VALUES(?,?)',[participant.sessionId,id]);}
    this.db.run("UPDATE desktop_runs SET state='active',deadline=?,lease_holder=?,lease_epoch=lease_epoch+1,lease_until=?,revision=revision+1 WHERE id=?",[this.now()+JSON.parse(r.limits).maxSeconds*1000,holder,this.now()+300000,id]);this.db.run('UPDATE desktop_run_consents SET expires_at=? WHERE run_id=? AND revoked_at IS NULL',[this.row(id).deadline,id]);this.event(id,'started',actor??key(p),{holder,epoch:r.lease_epoch+1});return r.lease_epoch+1;
  }).immediate();}
  private active(id:string){const r=this.expire(id);if(r.state!=='active')throw new Error('Desktop collaboration is '+r.state);const l=desktopLimitsSchema.parse(JSON.parse(r.limits));if(l.maxMessages!==null&&r.messages_used>=l.maxMessages){this.terminal(id,'limit_reached','message_budget','core');throw new Error('Message budget exhausted');}return r;}
  reserve(id:string,p:Principal,messageId:string,body:string,replyTo?:string,task?:Task){
    uuid.parse(messageId);if(!body.trim()||body.length>32000)throw new Error('Message body must contain 1–32000 characters');if(task)taskSchema.parse(task);
    return this.db.transaction(()=>{const r=this.row(id);this.member(r,p);const dst=(JSON.parse(r.participants) as Participant[]).find(x=>!same(x,p))!;const digest=hash({src:key(p),dst:key(dst),body,replyTo,task});const old=this.db.query<MessageRow,[string]>('SELECT * FROM desktop_messages WHERE id=?').get(messageId);
      if(old){if(old.run_id!==id||old.request_hash!==digest)throw new Error('Message ID reused with different content');return {reused:true,message:old,header:null,bootstrap:false};}
      const current=this.active(id);const allowed=this.coordination.sendAllowed(id,current.context_version,task);if(!allowed.allowed)throw new Error(allowed.reason);if(current.messages_used===0&&current.initiator!==key(p))throw new Error('The initiator sends the first bootstrap');if(current.lease_until===null||current.lease_until<=this.now()||!this.executorAlive(current.lease_holder))throw new Error('Executor lease expired; explicit recovery required');
      if(this.db.query("SELECT 1 FROM desktop_messages WHERE run_id=? AND status IN('reserved','submitting','unknown')").get(id))throw new Error('Uncertain delivery; inspect before new work, never resend');
      if(replyTo){const previous=this.db.query<MessageRow,[string]>('SELECT * FROM desktop_messages WHERE id=?').get(replyTo);if(!previous||previous.run_id!==id||previous.dst!==key(p)||previous.context_version!==current.context_version||!['delivered','started','steered','consumed','socket-written'].includes(previous.status))throw new Error('Reply must reference a current message addressed to this caller');}
      if(task&&this.coordination.status(id,current.context_version).structured)this.coordination.assign(id,{assigner:key(p),assignee:key(dst),contextVersion:current.context_version,messageId,task});
      const capability=randomBytes(32).toString('hex');this.db.run("INSERT INTO desktop_messages VALUES(?,?,?,?,?,?,?,?,'reserved',?,NULL,?,?,0,?,0)",[messageId,id,key(p),key(dst),current.context_version,body,digest,hash(capability),current.lease_epoch,replyTo??null,task?JSON.stringify(task):null,this.now()]);
      if(current.messages_used===0)this.db.run('INSERT INTO desktop_bootstraps VALUES(?,?)',[id,messageId]);this.db.run('UPDATE desktop_runs SET messages_used=messages_used+1,lease_until=? WHERE id=? AND lease_epoch=?',[this.now()+300000,id,current.lease_epoch]);this.event(id,'message_reserved',key(p),{messageId,src:key(p),dst:key(dst),contextVersion:current.context_version});return {reused:false,bootstrap:current.messages_used===0,message:this.message(messageId)!,header:{runId:id,messageId,capability,contextVersion:current.context_version,...(replyTo?{replyTo}:{})} satisfies Header};
    }).immediate();
  }
  abandon(id:string,p:Principal,messageId:string,reason:string){return this.db.transaction(()=>{this.member(this.row(id),p);const changed=this.db.run("UPDATE desktop_messages SET status='not-sent' WHERE id=? AND run_id=? AND src=? AND status='reserved' AND transport_id IS NULL",[messageId,id,key(p)]);if(changed.changes){this.db.run("UPDATE desktop_runs SET state='blocked',reason=?,revision=revision+1 WHERE id=? AND state='active'",[reason,id]);this.event(id,'reserved_abandoned',key(p),{messageId,reason,budgetRefunded:false});}}).immediate();}
  message(id:string){return this.db.query<MessageRow,[string]>('SELECT * FROM desktop_messages WHERE id=?').get(id);}
  claim(id:string,p:Principal,messageId:string,transportId:string,epoch:number,wire:string){return this.db.transaction(()=>{const r=this.expire(id);this.member(r,p);if(r.state!=='active'||r.lease_epoch!==epoch||(r.lease_until??0)<=this.now()||!this.executorAlive(r.lease_holder))throw new Error('Stale executor epoch or inactive run');const n=this.db.run("UPDATE desktop_messages SET status='submitting',transport_id=? WHERE id=? AND run_id=? AND src=? AND status='reserved' AND epoch=?",[uuid.parse(transportId),messageId,id,key(p),epoch]);if(n.changes!==1)throw new Error('Attempt already claimed; do not resend');this.db.run('INSERT INTO desktop_wires VALUES(?,?)',[messageId,hash(wire)]);}).immediate();}
  fence(id:string,epoch:number){const r=this.expire(id);return r.state==='active'&&r.lease_epoch===epoch&&(r.lease_until??0)>this.now()&&this.executorAlive(r.lease_holder);}
  transport(transportId:string,status:string){this.db.transaction(()=>{const m=this.db.query<MessageRow,[string]>('SELECT * FROM desktop_messages WHERE transport_id=?').get(transportId);if(!m)return;if(status==='socket-written'&&!['reserved','submitting'].includes(m.status))return;if(m.status==='consumed')return;this.db.run('UPDATE desktop_messages SET status=? WHERE id=?',[status,m.id]);this.event(m.run_id,'transport_status','transport',{messageId:m.id,status});if(['unknown','denied','held','refused','dropped','not-sent'].includes(status)){this.db.run("UPDATE desktop_runs SET state='blocked',reason=?,revision=revision+1 WHERE id=? AND state='active'",['transport:'+status,m.run_id]);}}).immediate();}
  admit(receiver:Principal,sender:Principal,header:Header,transportId:string,wire:string){return this.db.transaction(()=>{const r=this.expire(header.runId),m=this.message(header.messageId);if(!m||m.run_id!==r.id||m.src!==key(sender)||m.dst!==key(receiver)||m.transport_id!==transportId||m.cap_hash!==hash(header.capability)||m.context_version!==header.contextVersion||r.context_version!==header.contextVersion||m.epoch!==r.lease_epoch||r.state!=='active')return false;
    const saved=this.db.query<{wire_hash:string},[string]>('SELECT wire_hash FROM desktop_wires WHERE message_id=?').get(m.id);if(!saved||saved.wire_hash!==hash(wire)||m.delivery_claimed)return false;if(m.authorized)return true;this.db.run('UPDATE desktop_messages SET authorized=1 WHERE id=? AND authorized=0',[m.id]);const bootstrap=this.db.query<{message_id:string},[string]>('SELECT * FROM desktop_bootstraps WHERE run_id=?').get(r.id);if(m.src===r.initiator&&r.initiator.startsWith('claude:'))this.db.run('UPDATE desktop_run_consents SET used_bootstrap_message_id=? WHERE run_id=? AND used_bootstrap_message_id IS NULL',[m.id,r.id]);this.event(r.id,'recipient_admission',key(receiver),{messageId:m.id,attribution:'local_capability',budgetCountedAtReservation:true});return true;
  }).immediate();}
  claimRecipient(transportId:string){return this.db.transaction(()=>{const m=this.db.query<MessageRow,[string]>('SELECT * FROM desktop_messages WHERE transport_id=?').get(transportId);if(!m)return null;const r=this.expire(m.run_id);if(r.state!=='active'||m.context_version!==r.context_version||m.epoch!==r.lease_epoch||!m.authorized)return false;return this.db.run('UPDATE desktop_messages SET delivery_claimed=1 WHERE id=? AND delivery_claimed=0',[m.id]).changes===1;}).immediate();}
  byTransport(id:string){return this.db.query<MessageRow,[string]>('SELECT * FROM desktop_messages WHERE transport_id=?').get(id);}
  nativeIntent(transportId:string,inputId:string){if(this.byTransport(transportId))this.db.run('INSERT OR IGNORE INTO desktop_deliveries VALUES(?,?,NULL)',[transportId,uuid.parse(inputId)]);}
  nativeConsumed(transportId:string,inputId:string){if(this.db.run('UPDATE desktop_deliveries SET consumed_at=? WHERE transport_id=? AND input_id=? AND consumed_at IS NULL',[this.now(),transportId,inputId]).changes)this.transport(transportId,'consumed');}
  report(id:string,p:Principal,reportId:string,raw:Report,text:string,recordedContextVersion?:number){return this.db.transaction(()=>{const r=this.expire(id);this.member(r,p);if(r.state!=='active')throw new Error('Cannot report in '+r.state);const report=reportSchema.parse(raw),reportContext=recordedContextVersion??r.context_version;if(reportContext!==r.context_version&&(report.kind!=='result'||!this.db.query('SELECT 1 FROM desktop_contexts WHERE run_id=? AND version=?').get(id,reportContext)))throw new Error('Invalid captured result context');if(!text.trim()||text.length>32000)throw new Error('Invalid report body');const h=hash({author:key(p),report,text,version:reportContext}),old=this.db.query<{content_hash:string},[string]>('SELECT * FROM desktop_reports WHERE id=?').get(uuid.parse(reportId));if(old){if(old.content_hash!==h)throw new Error('Report ID reused');return;}
    const structured=this.coordination.status(id,r.context_version).structured;if(structured&&reportContext===r.context_version)this.coordination.validate(id,key(p),reportContext,report);
    if(report.taskId&&!structured){const m=this.db.query<MessageRow,[string,string]>('SELECT * FROM desktop_messages WHERE run_id=? AND json_extract(task,\'$.taskId\')=?').get(id,report.taskId);if(!m||m.dst!==key(p)||m.context_version!==r.context_version)throw new Error('Wrong task author or context');if(report.kind==='review'){const task=taskSchema.parse(JSON.parse(m.task!));if(task.intent!=='review'||task.target?.resultId!==report.resultId||task.target.version!==report.version)throw new Error('Wrong review target');}}
    const all=this.reports(id);if(all.length>=500)throw new Error('Report limit reached');if(report.kind==='result'){const versions=all.filter(x=>x.report.kind==='result'&&x.report.resultId===report.resultId);if(versions.some(x=>x.author!==key(p))||report.version!==1+Math.max(0,...versions.map(x=>x.report.kind==='result'?x.report.version:0)))throw new Error('Result versions must be sequential, immutable and authored');}
    if(report.kind==='review'&&!all.some(x=>x.contextVersion===r.context_version&&x.report.kind==='result'&&x.report.resultId===report.resultId&&x.report.version===report.version))throw new Error('Review target is absent or stale');
    this.db.run('INSERT INTO desktop_reports VALUES(?,?,?,?,?,?,?,?)',[reportId,id,key(p),reportContext,JSON.stringify(report),text,h,this.now()]);if(structured&&reportContext===r.context_version)this.coordination.complete(id,key(p),reportId,reportContext,report);this.event(id,'agent_report',key(p),{reportId,declared:true,validatedByCore:false});
  }).immediate();}
  private reports(id:string){return this.db.query<{id:string;author:string;context_version:number;payload:string;body:string;content_hash:string;created_at:number},[string]>('SELECT * FROM desktop_reports WHERE run_id=? ORDER BY rowid').all(id).map(x=>({...x,report:reportSchema.parse(JSON.parse(x.payload)),contextVersion:x.context_version,contentHash:hash(x.body),declared:true,validatedByCore:false}));}
  control(id:string,p:Principal,actionId:string,expectedRevision:number,action:{action:'pause'|'resume'|'cancel'|'finish'|'recover'|'context'|'phase'|'task';context?:unknown;phase?:DesktopPhase;task?:Task;assignee?:'self'|'peer';coordinationRevision?:number;closure?:Closure},holder:string,panel:string|false=false){return this.db.transaction(()=>{const r=this.expire(id);if(panel)this.member(r,p);else this.owner(r,p);uuid.parse(actionId);const digest=hash({id,p,expectedRevision,action,panel}),old=this.db.query<{request_hash:string;result:string},[string]>('SELECT * FROM desktop_actions WHERE id=?').get(actionId);if(old){if(old.request_hash!==digest)throw new Error('Action ID reused');return JSON.parse(old.result);}
    if(r.revision!==expectedRevision)throw new Error('Revision changed; inspect before control');if(['completed','cancelled','limit_reached'].includes(r.state)||(r.state==='prepared'&&action.action!=='cancel'))throw new Error('Cannot control '+r.state);const actor=panel||key(p);
    if(action.action==='cancel'||action.action==='finish'){if(action.closure){const reports=this.reports(id),target=action.closure.result,result=target?reports.find(q=>q.report.kind==='result'&&q.report.resultId===target.resultId&&q.report.version===target.version):null,all=this.status(id,p);this.coordination.close(id,key(p),action.closure,{contextVersion:r.context_version,result:result&&result.report.kind==='result'?{resultId:result.report.resultId,version:result.report.version,author:result.author,contentHash:result.contentHash,contextVersion:result.contextVersion}:null,reviews:all.reviews.map(q=>{if(q.report.kind!=='review')throw new Error('Invalid review');return {author:q.author,resultId:q.report.resultId,version:q.report.version,verdict:q.report.verdict,contextVersion:q.contextVersion,current:q.current,disagreements:q.report.disagreements}})});}this.terminal(id,action.action==='cancel'?'cancelled':'completed',action.action,actor);}
    else {if(action.action==='recover'){if((r.lease_until??0)>this.now()&&r.lease_holder!==holder&&this.executorAlive(r.lease_holder))throw new Error('Another live executor holds the lease');this.db.run("UPDATE desktop_messages SET status='not-sent' WHERE run_id=? AND status='reserved' AND transport_id IS NULL",[id]);this.db.run("UPDATE desktop_runs SET lease_epoch=lease_epoch+1,lease_holder=?,lease_until=?,state='paused',reason='recovered_paused' WHERE id=?",[holder,this.now()+300000,id]);}
      else {if(action.action!=='pause'&&(r.lease_holder!==holder||!this.fenceForControl(r)))throw new Error('Control requires the current executor lease');
        if(action.action==='pause')this.db.run("UPDATE desktop_runs SET state='paused' WHERE id=?",[id]);
        if(action.action==='resume'){if(this.db.query("SELECT 1 FROM desktop_messages WHERE run_id=? AND status IN('reserved','submitting','unknown')").get(id))throw new Error('Uncertain delivery is never replayed');this.db.run("UPDATE desktop_runs SET state='active',reason=NULL WHERE id=?",[id]);}
        if(action.action==='phase')this.coordination.phase(id,actor,actionId,action.coordinationRevision??-1,action.phase!,r.context_version);
        if(action.action==='task'){const assigned=action.assignee==='peer'?(JSON.parse(r.participants) as Participant[]).find(x=>!same(x,p))!:p;this.coordination.assign(id,{assigner:key(p),assignee:key(assigned),contextVersion:r.context_version,task:action.task!});}
        if(action.action==='context'){const c=contextSchema.parse(action.context);if(this.db.query("SELECT 1 FROM desktop_messages WHERE run_id=? AND status IN('reserved','submitting','unknown')").get(id))throw new Error('Resolve uncertain delivery before context');this.db.run('INSERT INTO desktop_contexts VALUES(?,?,?)',[id,r.context_version+1,JSON.stringify(c)]);this.db.run('UPDATE desktop_runs SET context=?,context_version=context_version+1 WHERE id=?',[JSON.stringify(c),id]);this.coordination.contextChanged(id,r.context_version+1);}}
      this.db.run('UPDATE desktop_runs SET revision=revision+1 WHERE id=?',[id]);this.event(id,'control',actor,{action:action.action,epoch:this.row(id).lease_epoch});}
    const result={revision:this.row(id).revision,state:this.row(id).state};this.db.run('INSERT INTO desktop_actions VALUES(?,?,?,?)',[actionId,id,digest,JSON.stringify(result)]);return result;
  }).immediate();}
  private fenceForControl(r:RunRow){return (r.lease_until??0)>this.now();}
  status(id:string,p:Principal,panel=false){const r=this.db.transaction(()=>this.expire(id)).immediate();this.member(r,p);const reports=this.coordination.visibleReports(id,key(p),r.context_version,this.reports(id)),structured=this.coordination.status(id,r.context_version),results=reports.filter(x=>x.report.kind==='result');const reviews=reports.filter(x=>x.report.kind==='review').map(x=>{const q=x.report;if(q.kind!=='review')throw new Error('Invalid review');const versions=results.filter(y=>y.report.kind==='result'&&y.report.resultId===q.resultId);const target=versions.find(y=>y.report.kind==='result'&&y.report.version===q.version);return {...x,current:x.contextVersion===r.context_version&&target?.contextVersion===r.context_version&&q.version===Math.max(0,...versions.map(y=>y.report.kind==='result'?y.report.version:0)),targetHash:target?.contentHash??null};});
    return {schemaVersion:'desktop_v2',id:r.id,initiator:{provider:r.initiator.split(':')[0] as 'codex'|'claude',sessionId:r.initiator.split(':')[1]!},ownerThread:r.initiator.split(':')[1]!,state:r.state,reason:r.reason,createdAt:r.created_at,contextVersion:r.context_version,context:contextSchema.parse(JSON.parse(r.context)),routine:JSON.parse(r.routine),limits:desktopLimitsSchema.parse(JSON.parse(r.limits)),messagesUsed:r.messages_used,deadline:r.deadline,participants:JSON.parse(r.participants) as Participant[],consent:this.consentStatus(id),coordination:{revision:r.revision,lease:{holder:r.lease_holder,epoch:r.lease_epoch,expiresAt:r.lease_until},barrierOpen:!structured.structured||structured.barrierOpen,structured},reports,results,reviews,validatedConsensus:false,messages:this.db.query<MessageRow,[string]>('SELECT * FROM desktop_messages WHERE run_id=? ORDER BY rowid').all(id).map(({cap_hash,body,...m})=>({...m,src:{provider:m.src.split(':')[0],sessionId:m.src.split(':')[1]},dst:{provider:m.dst.split(':')[0],sessionId:m.dst.split(':')[1]},text:m.authorized||['socket-written','delivered','consumed'].includes(m.status)?body:null,attribution:m.dst.startsWith('claude:')?'authenticated_mcp_caller':'local_capability',recipientAdmission:m.dst.startsWith('claude:')?'native_claude_not_observed':m.authorized?'core_admitted':'not_admitted'})),events:this.db.query<{sequence:number;type:string;actor:string;at:number;payload:string},[string]>('SELECT * FROM desktop_events WHERE run_id=? ORDER BY sequence').all(id).map(e=>({...e,payload:JSON.parse(e.payload)}))};
  }
  list(p:Principal,panel=false){return this.db.query<{id:string;participants:string},[]>('SELECT id,participants FROM desktop_runs ORDER BY created_at DESC').all().filter(r=>(JSON.parse(r.participants) as Participant[]).some(x=>same(x,p))).map(r=>this.status(r.id,p,panel));}
}

export function parseDesktopMessage(text:string){const body=/^<cross-session-message\s[^>]*>\n([\s\S]*)\n<\/cross-session-message>$/.exec(text)?.[1]??text;if(!body.startsWith(desktopPrefix))return null;const end=body.indexOf('\n');if(end<0||end>2048)throw new Error('Invalid Desktop header');return {header:desktopHeaderSchema.parse(JSON.parse(body.slice(desktopPrefix.length,end))),text:body.slice(end+1)};}
